export const zh = {
  common: {
    login: '登录',
    register: '注册',
    logout: '退出登录',
    submit: '提交',
    cancel: '取消',
    confirm: '确定',
    close: '关闭',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    search: '搜索',
    save: '保存',
    reset: '重置',
    back: '返回',
    success: '操作成功',
    failed: '操作失败',
    loading: '加载中...',
    noData: '暂无数据',
    confirmDelete: '确定要删除吗？',
    tip: '提示',
    all: '全部',
    name: '名称',
    code: '代码',
    department: '院系',
    class: '班级',
    user: '用户',
    admin: '管理员',
    teacher: '教师',
    student: '学生',
    role: '角色',
    username: '用户名',
    password: '密码',
    email: '邮箱',
    phone: '手机号',
    realName: '真实姓名',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    pleaseEnter: '请输入',
    pleaseSelect: '请选择',
    notModifyLeaveEmpty: '不修改请留空',
    per: '每',
    distribution: '分布',
    remark: '备注',
    participation: '参与人次',
    exam: '考试',
    paper: '试卷',
    question: '题目',
    score: '分数',
    time: '时间',
    status: '状态',
    statistics: '统计',
    logs: '日志',
    overview: '概览',
    dashboard: '首页',
    account: '个人中心',
    message: '消息',
    language: '语言',
    chinese: '中文',
    english: 'English',
    myClasses: '我的班级',
    history: '考试历史',
    wrongQuestions: '错题本',
    examList: '考试列表',
    takeExam: '开始考试',
    viewDetail: '查看详情',
    grade: '评分',
    monitor: '监控',
    manage: '管理',
    subject: '科目',
    knowledgePoint: '知识点',
    paperManage: '试卷管理',
    questionManage: '题库管理',
    subjectManage: '科目管理',
    examManage: '考试管理',
    examRecord: '考试记录',
    systemLog: '系统日志',
    userManage: '用户管理',
    departmentManage: '院系管理',
    classManage: '班级管理',
    dataStatistics: '数据统计',
    leftCount: '离开次数',
    maxLeaveCount: '最大离开次数',
    leaveDetection: '离开检测',
    shuffleQuestions: '题目乱序',
    shuffleOptions: '选项乱序',
    passRate: '及格比例',
    viewAfterExam: '考后查看',
    duration: '时长(分钟)',
    startTime: '开始时间',
    endTime: '结束时间',
    title: '标题',
    content: '内容',
    options: '选项',
    correctAnswer: '正确答案',
    type: '类型',
    singleChoice: '单选题',
    multipleChoice: '多选题',
    trueFalse: '判断题',
    fillBlank: '填空题',
    shortAnswer: '简答题',
    single: '单选题',
    multiple: '多选题',
    judgment: '判断题',
    essay: '简答题',
    detail: '查看详情',
    pending: '待开始',
    notStarted: '未开始',
    ongoing: '进行中',
    finished: '已结束',
    submitted: '已提交',
    notSubmitted: '未提交',
    autoSave: '自动保存',
    manualSave: '手动保存',
    submitExam: '提交考试',
    timeRemaining: '剩余时间',
    seconds: '秒',
    minutes: '分钟',
    hours: '小时',
    today: '今天',
    yesterday: '昨天',
    thisWeek: '本周',
    thisMonth: '本月',
    total: '总计',
    average: '平均',
    count: '数量',
    percent: '百分比',
    date: '日期',
    operation: '操作',
    method: '方法',
    ip: 'IP地址',
    createTime: '创建时间',
    updateTime: '更新时间',
    inviteCode: '邀请码',
    members: '成员',
    messages: '消息',
    send: '发送',
    join: '加入',
    leave: '离开',
    upload: '上传',
    avatar: '头像',
    about: '关于',
    version: '版本',
    copyright: '版权所有',
    clearCache: '清除缓存',
    changePassword: '修改密码',
    editProfile: '编辑资料',
    welcome: '欢迎',
    recentExam: '最近考试',
    upcomingExam: '待考考试',
    completedExam: '已完成考试',
    examNotice: '考试须知',
    logRecent: '最近操作',
    viewMore: '查看更多',
    noMore: '没有更多了',
    page: '页',
    of: '共',
    goToPage: '跳转到',
    rowsPerPage: '每页条数',
    prevPage: '上一页',
    nextPage: '下一页',
    firstPage: '首页',
    lastPage: '末页',
    loginSuccess: '登录成功',
    registerSuccess: '注册成功',
    passwordChanged: '密码修改成功',
    profileUpdated: '资料更新成功',
    pleaseLogin: '请先登录',
    sessionExpired: '登录已过期，请重新登录',
    networkError: '网络错误',
    serverError: '服务器错误',
    notFound: '未找到',
    forbidden: '无权访问',
    examStarted: '考试已开始',
    examFinished: '考试已结束',
    examNotStarted: '考试尚未开始',
    examSubmitted: '已提交试卷',
    leaveWarning: '检测到离开考试页面',
    exceedLeaveCount: '离开次数过多，已自动交卷',
    leaveCount: '离开次数',
    pleaseAnswerAll: '请完成所有题目后再提交',
    confirmSubmit: '确定要提交试卷吗？',
    savedSuccessfully: '保存成功',
    saveFailed: '保存失败',
    loadingMore: '加载更多...',
    enterExam: '进入考试',
    viewPaper: '查看试卷',
    viewScore: '查看成绩',
    viewAnalysis: '查看分析',
    practice: '练习',
    mastered: '已掌握',
    notMastered: '未掌握',
    correctRate: '正确率',
    correct: '正确',
    wrong: '错误',
    difficulty: '难度',
    frequency: '错误次数',
    publish: '发布',
    unpublish: '取消发布',
    start: '开始',
    finish: '结束',
    extend: '延长',
    extendMinutes: '延长分钟数',
    generate: '生成',
    import: '导入',
    export: '导出',
    copy: '复制',
    copied: '已复制',
    selectAll: '全选',
    deselectAll: '取消全选',
    invertSelect: '反选',
    selectedCount: '已选 {count} 项',
    batchDelete: '批量删除',
    batchOperation: '批量操作',
    batchSuccess: '批量操作成功',
    batchFailed: '批量操作失败',
    selectDepartment: '选择院系',
    selectSubject: '选择科目',
    selectQuestionType: '选择题型',
    selectRole: '选择角色',
    selectStatus: '选择状态',
    selectDate: '选择日期',
    startDate: '开始日期',
    endDate: '结束日期',
    selectTime: '选择时间',
    quickSelect: '快捷选择',
    customRange: '自定义范围',
    searchPlaceholder: '请输入关键词',
    filterPlaceholder: '请选择筛选条件',
    resetFilter: '重置筛选',
    applyFilter: '应用筛选',
    filterResult: '共 {count} 条结果',
    sortAsc: '升序',
    sortDesc: '降序',
    sortBy: '排序方式',
    sortByName: '按名称排序',
    sortByTime: '按时间排序',
    sortByCount: '按数量排序',
    sortByScore: '按分数排序',
    ascending: '升序',
    descending: '降序',
    show: '显示',
    hide: '隐藏',
    expand: '展开',
    collapse: '折叠',
    toggle: '切换',
    enable: '启用',
    disable: '禁用',
    switch: '开关',
    on: '开',
    off: '关',
    yes: '是',
    no: '否',
    unknown: '未知',
    other: '其他',
    pleaseWait: '请稍候',
    processing: '处理中...',
    complete: '完成',
    confirmLogout: '确定要退出登录吗？',
    examCreatedSuccess: '考试创建成功',
    examUpdatedSuccess: '考试更新成功',
    examDeletedSuccess: '考试删除成功',
    examPublishedSuccess: '考试发布成功',
    examUnpublishedSuccess: '考试已取消发布',
    paperCreatedSuccess: '试卷创建成功',
    paperUpdatedSuccess: '试卷更新成功',
    paperDeletedSuccess: '试卷删除成功',
    questionCreatedSuccess: '题目创建成功',
    questionUpdatedSuccess: '题目更新成功',
    questionDeletedSuccess: '题目删除成功',
    subjectCreatedSuccess: '科目创建成功',
    subjectUpdatedSuccess: '科目更新成功',
    subjectDeletedSuccess: '科目删除成功',
    userCreatedSuccess: '用户创建成功',
    userUpdatedSuccess: '用户更新成功',
    userDeletedSuccess: '用户删除成功',
    departmentCreatedSuccess: '院系创建成功',
    departmentUpdatedSuccess: '院系更新成功',
    departmentDeletedSuccess: '院系删除成功',
    classCreatedSuccess: '班级创建成功',
    classUpdatedSuccess: '班级更新成功',
    classDeletedSuccess: '班级删除成功',
    joinedClassSuccess: '加入班级成功',
    leftClassSuccess: '退出班级成功',
    messageSentSuccess: '消息发送成功',
    examSubmittedSuccess: '考试提交成功',
    examGradedSuccess: '评分成功',
    statisticsUpdated: '统计数据已更新',
    logsCleared: '日志已清空',
    cacheCleared: '缓存已清除',
    welcomeBack: '欢迎回来',
    hello: '你好',
    goodbye: '再见',
    haveANiceDay: '祝你愉快',
    seeYouLater: '再见',
    goodLuck: '祝你好运',
    congratulations: '恭喜',
    wellDone: '做得好',
    excellent: '太棒了',
    greatJob: '干得好',
    niceWork: '做得不错',
    thankYou: '谢谢',
    statusPending: '待开始',
    statusOngoing: '进行中',
    statusFinished: '已结束',
    systemManagement: '系统管理',
    userManagement: '用户管理',
    departmentManagement: '院系管理',
    classManagement: '班级管理',
    dataStatistics: '数据统计',
    systemLogs: '系统日志',
    recentLogs: '最近操作日志',
    recentExams: '最近考试',
    manageExams: '管理考试',
    upcomingExams: '待考考试',
    allExams: '全部考试',
    waiting: '等待开始',
    noUpcomingExams: '暂无待考考试',
    examTips: '考试须知',
    subjectManagement: '科目管理',
    questionManagement: '题库管理',
    paperManagement: '试卷管理',
    examManagement: '考试管理',
    scoreAnalysis: '成绩分析',
    allDepartments: '全部院系',
    noLogData: '暂无日志数据',
    totalRecords: '共 {total} 条记录',
    year: '年',
    month: '月',
    day: '日',
    saving: '保存中...',
    saveSuccess: '保存成功',
    saveFailed: '保存失败',
    creator: '创建者',
    unknownUser: '未知用户',
    classMembers: '班级成员',
    muted: '已禁言',
    sendFailed: '发送失败',
    enterMessage: '输入消息...',
    justNow: '刚刚',
    minutesAgo: '分钟前',
    hoursAgo: '小时前',
    createUser: '创建用户',
    updateUser: '更新用户',
    deleteUser: '删除用户',
    createDepartment: '创建院系',
    updateDepartment: '更新院系',
    deleteDepartment: '删除院系',
    createClass: '创建班级',
    updateClass: '更新班级',
    deleteClass: '删除班级',
    createExam: '创建考试',
    updateExam: '更新考试',
    deleteExam: '删除考试',
    editExam: '编辑考试',
    basicInfo: '基本信息',
    id: 'ID',
    viewAnswer: '查看答案',
    allExams: '全部考试',
    questionCount: '题目数量',
    judgment: '判断题',
    essay: '简答题',
    inviteMembers: '邀请成员',
    importText: '导入文本',
    formatDesc: '格式说明',
    importNote: '导入注意事项',
    target: '目标',
    shuffleQuestions: '题目乱序',
    shuffleOptions: '选项乱序',
    leaveDetection: '离开检测',
    passRate: '及格比例',
    allowViewAfterExam: '允许考后查看',
    examDuration: '考试时长（分钟）',
    selectPaper: '选择试卷',
    selectClass: '选择班级',
    startDate: '开始日期',
    startTime: '开始时间',
    examSettings: '考试设置',
    selectStartTime: '请选择开始时间',
    publishExam: '发布考试',
    inviteMembers: '邀请成员'
  },
  student: {
    viewLatest: '查看班级最新动态',
    viewAndJoin: '查看并参加待进行的考试',
    searchExam: '搜索考试名称',
    viewExamHistory: '查看已完成考试的成绩和答卷详情',
    submitTime: '交卷时间',
    autoSubmitted: '强制收卷',
    viewAnalysis: '查看您的学习数据分析',
    subjectScores: '科目成绩',
    timesExam: '次考试',
    answerStats: '答题情况',
    correctCount: '答对题数',
    wrongCount: '错题数',
    skippedCount: '未答题数',
    scoreTrend: '成绩趋势',
    knowledgeMastery: '知识点掌握情况',
    totalExams: '总考试数',
    averageScore: '平均分',
    highestScore: '最高分',
    wrongBookDesc: '自动收录所有答错的题目，支持反复练习',
    notMastered: '未学会',
    mastered: '已学会',
    questionContent: '题目内容',
    passRate: '通过百分比',
    practiceCount: '练习次数',
    viewAnswer: '查看答案',
    practice: '练习',
    markNotMastered: '标记未学会',
    markMastered: '标记已学会',
    wrongAnswer: '错误答案',
    notRecorded: '未记录',
    analysis: '解析',
    wrongPractice: '错题练习',
    enterAnswer: '请输入答案',
    answerCorrect: '回答正确',
    answerWrong: '回答错误',
    nextQuestion: '下一题',
    prevQuestion: '上一题',
    examInProgress: '考试中',
    submitExam: '交卷',
    questionNav: '题目导航',
    current: '当前',
    answered: '已答',
    unanswered: '未答',
    exam: '考试',
    score: '得分',
    scored: '已出分',
    pendingGrade: '待评分',
    save: '保存',
    questionUnit: '题',
    paperLocked: '教师已关闭考后查看试卷权限，无法查看试卷内容',
    question: '第',
    yourAnswer: '你的答案',
    loading: '加载中...',
    warning: '警告',
    leftExam: '您已离开考试页面！',
    leaveCount: '离开次数',
    remainingChances: '剩余',
    chancesLeft: '次机会，超出将自动交卷',
    reachedLimit: '已达到上限，即将自动交卷',
    continueExam: '继续作答',
    loadingExam: '加载考试信息...',
    classChat: {
      members: '名成员',
      startTime: '开始时间',
      endTime: '结束时间',
      duration: '考试时长',
      minutes: '分钟',
      enterExam: '进入考试',
      viewExam: '查看考试',
      enterMessage: '输入消息...',
      send: '发送',
      muted: '您已被禁言',
      classMembers: '班级成员',
      owner: '所有者',
      admin: '管理员',
      member: '成员'
    },
    selectSubject: '选择科目',
    selectStatus: '选择状态',
    search: '搜索',
    operation: '操作',
    type: '类型',
    status: '状态',
    close: '关闭',
    submit: '提交',
    correct: '正确',
    wrong: '错误',
    correctAnswer: '正确答案',
    single: '单选题',
    multiple: '多选题',
    judgment: '判断题',
    fillBlank: '填空题',
    essay: '简答题',
    programming: '编程题',
    account: {
      basicInfo: '基本资料',
      realName: '姓名',
      username: '学号/工号',
      phone: '手机号',
      email: '邮箱',
      enterRealName: '请输入姓名',
      enterPhone: '请输入手机号',
      enterEmail: '请输入邮箱',
      save: '保存修改',
      reset: '重置',
      avatar: '我的头像',
      uploadAvatar: '上传新头像',
      avatarTip: '支持 JPG、PNG 格式，大小不超过 2MB',
      password: '密码管理',
      changePassword: '修改密码',
      oldPassword: '旧密码',
      newPassword: '新密码',
      confirmPassword: '确认新密码',
      enterOldPassword: '请输入旧密码',
      enterNewPassword: '请输入新密码',
      confirmNewPassword: '请确认新密码',
      or: '或者',
      forgotPassword: '忘记旧密码？通过手机验证重置',
      enterPhoneLastSix: '请输入手机号后六位',
      sendCode: '发送验证码',
      secondsResend: '秒后重发',
      verificationCode: '验证码',
      enterVerificationCode: '请输入验证码',
      verifyAndReset: '验证并重置密码',
      account: '账号管理'
    },
    enterClassCode: '请输入班级群号',
    joinClass: '加入班级',
    noClass: '暂无班级，输入群号加入班级吧',
    loadFailed: '加载班级列表失败',
    joinSuccess: '加入班级成功',
    joinFailed: '加入班级失败',
    owner: '所有者',
    member: '普通成员',
    examStarted: '开始考试',
    examPublished: '发布通知',
    justNow: '刚刚',
    ago: '前',
    minutesAgo: ' minutes ago',
    hoursAgo: ' hours ago',
    examList: '考试列表',
    examHistory: '考试历史',
    wrongQuestions: '错题本',
    statistics: '成绩分析',
    account: '个人中心',
    noExams: '暂无考试',
    noHistory: '暂无考试记录',
    noWrongQuestions: '暂无错题',
    viewPaper: '查看试卷',
    viewScore: '查看成绩',
    viewAnalysis: '查看分析',
    practice: '练习',
    mastered: '已掌握',
    notMastered: '未掌握',
    correctRate: '正确率',
    frequency: '错误次数',
    totalScore: '总分',
    passScore: '及格分',
    duration: '时长',
    startTime: '开始时间',
    endTime: '结束时间',
    status: '状态',
    score: '分数',
    rank: '排名',
    average: '平均分',
    highest: '最高分',
    lowest: '最低分',
    subject: '科目',
    questionType: '题型',
    answer: '答案',
    correctAnswer: '正确答案',
    yourAnswer: '你的答案',
    analysis: '解析',
    myClasses: '我的班级',
    classChat: '班级聊天',
    sendMessage: '发送消息',
    noMessages: '暂无消息',
    examNotice: '考试通知',
    examEnded: '考试结束',
    enterExam: '进入考试',
    takeExam: '开始考试',
    submitExam: '提交考试',
    timeRemaining: '剩余时间',
    autoSave: '自动保存',
    confirmSubmit: '确定要提交试卷吗？',
    pleaseAnswerAll: '请完成所有题目后再提交',
    examSubmitted: '已提交',
    notSubmitted: '未提交',
    pending: '待开始',
    ongoing: '进行中',
    finished: '已结束',
    wrongCount: '错题数',
    completedCount: '已完成数',
    pendingCount: '待考数',
    scoreTrend: '成绩趋势',
    subjectAnalysis: '科目分析',
    questionAnalysis: '题型分析',
    personalBest: '个人最佳',
    improvement: '进步',
    needImprovement: '需要改进',
    studySuggestion: '学习建议',
    recentExam: '最近考试',
    upcomingExam: '待考考试',
    classInfo: '班级信息',
    classMembers: '班级成员',
    classActivities: '班级活动',
    leaveClass: '退出班级',
    confirmLeave: '确定要退出班级吗？',
    joinedSuccess: '加入成功',
    leftSuccess: '退出成功',
    classCode: '班级群号',
    classTeacher: '班主任',
    memberCount: '成员数量',
    lastActivity: '最后活动',
    activityType: '活动类型',
    examCreated: '创建考试',
    examPublished: '发布考试',
    examStarted: '开始考试',
    examFinished: '结束考试',
    messageSent: '发送消息',
    memberJoined: '成员加入',
    memberLeft: '成员退出',
    examName: '考试名称',
    examDate: '考试日期',
    examDuration: '考试时长',
    examScore: '考试成绩',
    examRank: '考试排名',
    viewDetails: '查看详情',
    retry: '重新练习',
    markMastered: '标记掌握',
    markNotMastered: '取消掌握',
    filterSubject: '筛选科目',
    filterMastery: '筛选掌握状态',
    allSubjects: '全部科目',
    allStatus: '全部状态',
    statisticsOverview: '统计概览',
    examHistory: '考试历史',
    learningProgress: '学习进度',
    knowledgePoints: '知识点',
    masteredCount: '已掌握',
    notMasteredCount: '未掌握',
    totalQuestions: '总题数',
    accuracyRate: '正确率',
    weakPoints: '薄弱环节',
    strongPoints: '强项',
    studyPlan: '学习计划',
    recommendedQuestions: '推荐题目',
    dailyGoal: '每日目标',
    completedToday: '今日完成',
    streak: '连续天数',
    achievements: '成就',
    totalExams: '总考试次数',
    totalScore: '总分',
    averageScore: '平均分',
    highestScore: '最高分',
    perfectScore: '满分次数',
    studyTime: '学习时长',
    questionsAnswered: '答题数',
    correctAnswers: '答对数',
    accuracy: '正确率',
    improvementRate: '进步率',
    rank: '排名',
    globalRank: '全球排名',
    classRank: '班级排名',
    schoolRank: '学校排名',
    shareResult: '分享成绩',
    downloadReport: '下载报告',
    printReport: '打印报告',
    exportData: '导出数据',
    importData: '导入数据',
    settings: '设置',
    notificationSettings: '通知设置',
    soundSettings: '声音设置',
    appearanceSettings: '外观设置',
    languageSettings: '语言设置',
    privacySettings: '隐私设置',
    about: '关于',
    version: '版本',
    feedback: '反馈',
    help: '帮助',
    contactUs: '联系我们',
    termsOfService: '服务条款',
    privacyPolicy: '隐私政策',
    copyright: '版权所有'
  },
  login: {
    usernamePlaceholder: '请输入用户名',
    passwordPlaceholder: '请输入密码',
    student: '学生',
    teacher: '教师',
    admin: '管理员',

    welcome: '欢迎回来',
    selectRole: '请选择登录身份',
    studentUsername: '请输入学生用户名',
    teacherUsername: '请输入教师用户名',
    adminUsername: '请输入管理员用户名',
    adminAccount: '请输入管理员账号',
    goRegister: '去注册',
    backToStudentTeacher: '回到学生/教师端',
    createAccount: '创建账号',
    registerInfo: '请选择身份并填写注册信息',
    confirmPassword: '请确认密码',
    selectDepartment: '请选择学院',
    goLogin: '去登录',
    slogan: '专业的在线考试系统，让学习更高效',
    feature1: '丰富的题型支持',
    feature2: '智能防作弊机制',
    feature3: '自动评分系统',
    feature4: '全面的数据分析',
    passwordNotMatch: '两次输入密码不一致',
    usernameLength: '用户名长度应为3-20个字符',
    passwordLength: '密码长度应为6-20个字符',
    studentNotFound: '不存在此学生账号',
    teacherNotFound: '不存在此教师账号',
    adminNotFound: '不存在此管理员账号'
  },
  dashboard: {
    welcome: '欢迎回来',
    totalUsers: '总用户数',
    count: '数',
    departmentCount: '院系数',
    classCount: '班级数',
    paperCount: '试卷数',
    questionCount: '题目数',
    examCount: '考试数',
    pendingExams: '待考考试',
    completedExams: '已完成',
    wrongCount: '错题数',
    averageScore: '平均分',
    scoreUnit: '分',
    myClasses: '我的班级',
    examList: '考试列表',
    examHistory: '考试历史',
    systemManagement: '系统管理',
    userManagement: '用户管理',
    departmentManagement: '院系管理',
    classManagement: '班级管理',
    dataStatistics: '数据统计',
    systemLogs: '系统日志',
    recentLogs: '最近操作日志',
    recentExams: '最近考试',
    manageExams: '管理考试',
    upcomingExams: '待考考试',
    allExams: '全部考试',
    enterExam: '进入考试',
    waiting: '等待开始',
    noUpcomingExams: '暂无待考考试',
    examTips: '考试须知',
    tip1: '进入考试后请保持网络畅通',
    tip2: '考试过程中请勿频繁切换页面',
    tip3: '答案会自动保存，但建议手动提交',
    tip4: '考试结束后可查看错题分析',
    subjectManagement: '科目管理',
    questionManagement: '题库管理',
    paperManagement: '试卷管理',
    examManagement: '考试管理',
    minutes: '分钟',
    scoreAnalysis: '成绩分析'
  },
  teacher: {
    viewLatest: '查看班级最新动态',
    examManagement: '考试管理',
    examManagementDesc: '发布和管理考试，监控考生状态',
    selectSubject: '选择科目',
    searchExamTitle: '搜索考试标题',
    selectExam: '选择考试',
    publishExam: '发布考试',
    id: 'ID',
    examTitle: '考试标题',
    totalScore: '总分',
    monitor: '监控',
    extend: '延时',
    stats: '统计',
    editExam: '修改考试',
    selectPaper: '选择试卷',
    selectClass: '选择班级',
    selectAtLeastOneClass: '请选择至少一个班级',
    selectPublishClass: '选择发布班级',
    selectStartTime: '选择开始时间',
    selectEndTime: '选择结束时间',
    examDuration: '考试时长',
    antiCheatSettings: '防作弊设置',
    maxLeaveCount: '离开次数上限',
    exceedAutoSubmit: '次，超过将自动收卷',
    postExamSettings: '考后设置',
    allowViewAfterExam: '允许考后查看试卷',
    viewAfterExamDesc: '开启后学生交卷即可查看试卷和得分',
    default60: '默认60',
    shuffleQuestionsDesc: '开启后题目顺序随机排列',
    shuffleOptionsDesc: '开启后选项顺序随机排列',
    leaveDetectionDesc: '检测考试期间离开页面',
    maxLeaveCountDesc: '超过此次数将自动收卷',
    allowViewAfterExamDesc: '考试结束后可查看试卷和答案',
    saveChanges: '保存修改',
    enterExamTitle: '请输入考试标题',
    getExamInfoFailed: '获取考试信息失败',
    publishSuccess: '发布成功',
    confirmStartExam: '确定要开始该考试吗？',
    examStarted: '考试已开始',
    confirmFinishExam: '确定要结束该考试吗？所有未交卷考生将自动交卷',
    examFinished: '考试已结束',
    enterExtendMinutes: '请输入延长时间（分钟）',
    extendExamTime: '延长考试时间',
    extendSuccess: '已延长考试时间',
    examMonitor: '考试监控',
    totalStudents: '总考生',
    submitted: '已交卷',
    autoSubmitted: '强制收卷',
    suspicious: '可疑',
    score: '得分',
    notStarted: '未开始',
    examStats: '考试统计',
    avgScore: '平均分',
    maxScore: '最高分',
    minScore: '最低分',
    classChat: {
      members: '名成员',
      startTime: '开始时间',
      endTime: '结束时间',
      duration: '考试时长',
      minutes: '分钟',
      enterExam: '进入考试',
      viewExam: '查看考试',
      enterMessage: '输入消息...',
      send: '发送',
      muted: '您已被禁言',
      classMembers: '班级成员',
      owner: '所有者',
      admin: '管理员',
      member: '成员'
    },
    paperManagement: '试卷管理',
    paperManagementDesc: '创建和管理考试试卷，支持手动组卷和自动组卷',
    paperTitle: '试卷标题',
    questionCount: '题数',
    publish: '发布',
    unpublish: '取消发布',
    createPaper: '创建试卷',
    editPaper: '编辑试卷',
    selectSubjectHint: '请选择科目',
    enterPaperTitle: '请输入试卷标题',
    passScore: '及格分',
    paperDuration: '时长(分钟)',
    duration: '时长',
    addQuestion: '添加题目',
    questionType: '题型',
    questionContent: '题目内容',
    options: '选项',
    correctAnswer: '正确答案',
    scoreHint: '分值',
    analysis: '解析',
    selectQuestionType: '选择题型',
    singleChoice: '单选题',
    multipleChoice: '多选题',
    judgment: '判断题',
    fillBlank: '填空题',
    essay: '简答题',
    programming: '编程题',
    paperPublished: '试卷已发布',
    paperUnpublished: '试卷已取消发布',
    paperCreated: '试卷创建成功',
    paperUpdated: '试卷更新成功',
    confirmUnpublish: '确定要取消发布该试卷吗？',
    confirmPublish: '确定要发布该试卷吗？',
    confirmDelete: '确定要删除该试卷吗？',
    draft: '草稿',
    published: '已发布',
    searchPaperTitle: '搜索试卷标题',
    autoGenerate: '自动组卷',
    preview: '预览',
    questionSettings: '题目设置',
    searchQuestion: '搜索题目',
    clearSelection: '清空选择',
    currentSubject: '当前科目',
    batchSetScore: '批量设置分值',
    applyToSelected: '应用到已选题目',
    setScore: '设置分值',
    selected: '已选择',
    questions: '题',
    scoreUnit: '分',
    selectSubjectFirst: '请先选择科目，才能添加题目',
    autoCalculate: '自动计算',
    enterDuration: '请输入考试时长',
    enterPassRate: '请输入及格百分比',
    questionCountScore: '题目数量与分值',
    count: '数量',
    perQuestion: '每题',
    generateTip1: '系统将从题库中随机抽取指定数量的题目自动生成试卷',
    generateTip2: '如果题库中某题型数量不足，组卷将失败',
    generatePaper: '生成试卷',
    generateResult: '组卷结果',
    studentPreview: '学生视角预览',
    current: '当前',
    unanswered: '未答',
    question: '第',
    prevQuestion: '上一题',
    nextQuestion: '下一题',
    noQuestion: '暂无题目',
    easy: '简单',
    medium: '中等',
    hard: '困难',
    enterScore: '请输入分值',
    batchSetSuccess: '批量设置成功',
    selectAtLeastOneQuestion: '请至少选择一道题目',
    selectAtLeastOneQuestionType: '请至少选择一种题型',
    getPaperInfoFailed: '获取试卷信息失败',
    enterAnswer: '请输入答案',
    questionManagement: '题库管理',
    questionManagementDesc: '管理考试题目，支持多种题型',
    keyword: '关键词',
    batchDelete: '批量删除',
    importQuestions: '导入题目',
    exportQuestions: '导出题目',
    viewQuestion: '查看题目',
    subject: '科目',
    content: '内容',
    operation: '操作',
    difficulty: '难度',
    frequency: '使用次数',
    correctRate: '正确率',
    enterContent: '请输入题目内容',
    enterOptions: '请输入选项（JSON格式）',
    enterAnswer: '请输入答案',
    enterAnalysis: '请输入解析',
    questionCreated: '题目创建成功',
    questionUpdated: '题目更新成功',
    questionDeleted: '题目删除成功',
    confirmDeleteQuestion: '确定要删除该题目吗？',
    confirmBatchDelete: '确定要删除选中的题目吗？',
    addQuestion: '新增题目',
    editQuestion: '编辑题目',
    batchImport: '批量导入',
    searchQuestion: '搜索题目',
    optionCount: '选项数量',
    optionUnit: '个选项',
    enterOption: '请输入',
    correctAnswer: '正确答案',
    referenceAnswer: '参考答案',
    fillBlankPlaceholder: '输入题目内容，在需要填空的位置输入 $blank$',
    insertBlank: '插入填空标记',
    blankHint: '点击按钮在光标位置插入 "$blank$" 作为填空标记',
    fillBlankAnswerPlaceholder: '多个空用英文逗号分隔，如：答案1,答案2,答案3',
    questionText: '题目文本',
    importPlaceholder: '请粘贴题目文本，支持以下格式：\n\n1. 单选题：\n1. 题目内容\nA. 选项一\nB. 选项二\nC. 选项三\nD. 选项四\n答案：B\n\n2. 多选题：\n2. 题目内容（多选）\nA. 选项一\nB. 选项二\nC. 选项三\nD. 选项四\n答案：A,B\n\n3. 判断题：\n3. 题目内容（对）\n或\n3. 题目内容（错）\n\n4. 填空题：\n4. 题目内容（答案：填空答案）\n\n5. 简答题：\n5. 题目内容\n（参考答案：答案内容）',
    formatInstructions: '格式说明',
    questionNumbering: '题目编号',
    numberingFormat: '支持"1."、"一、"、"（一）"等格式',
    optionFormat: '选项格式',
    optionFormatDesc: '使用"A."、"B."、"C."、"D."开头',
    answerMark: '答案标记',
    answerMarkDesc: '单独一行写"答案：A"或"答案：A,B"',
    judgmentFormat: '判断题',
    judgmentFormatDesc: '在题目末尾添加"（对）"或"（错）"',
    fillBlankFormat: '填空题',
    fillBlankFormatDesc: '使用"（答案：xxx）"或"【答案xxx】"',
    essayFormat: '简答题',
    essayFormatDesc: '使用"（参考答案：xxx）"',
    startImport: '开始导入',
    importResult: '导入结果',
    success: '成功',
    failed: '失败',
    failedDetails: '失败详情',
    enterQuestionText: '请输入题目文本',
    importFailed: '导入失败',
    importFailedRetry: '导入失败，请稍后重试',
    correct: '正确',
    incorrect: '错误',
    subjectManagement: '科目管理',
    subjectManagementDesc: '管理考试科目',
    subjectName: '科目名称',
    subjectCode: '科目代码',
    description: '描述',
    createSubject: '创建科目',
    editSubject: '编辑科目',
    searchSubject: '搜索科目',
    enterSubjectName: '请输入科目名称',
    enterSubjectCode: '请输入科目代码',
    enterDescription: '请输入描述',
    confirmDeleteSubject: '确定要删除该科目吗？',
    subjectCreated: '科目创建成功',
    subjectUpdated: '科目更新成功',
    subjectDeleted: '科目删除成功',
    examRecordManagement: '阅卷与成绩管理',
    examRecordManagementDesc: '查看考试成绩统计，进行错题分析',
    examName: '考试名称',
    exportScores: '导出成绩',
    scoreStatistics: '成绩统计',
    highestScore: '最高分',
    lowestScore: '最低分',
    averageScore: '平均分',
    passRate: '及格率',
    totalStudents: '参考人数',
    passCount: '及格人数',
    wrongQuestionAnalysis: '错题分析',
    questionId: '题目ID',
    questionContent: '题目内容',
    questionType: '题型',
    score: '分值',
    totalAnswered: '答题人数',
    correctCount: '正确人数',
    studentScoreList: '学生成绩列表',
    studentName: '学生姓名',
    screenSwitchCount: '切屏次数',
    suspicious: '可疑',
    startTime: '开始时间',
    submitTime: '交卷时间',
    detailInDevelopment: '查看详情功能开发中',
    csvHeader: '学生ID,成绩,交卷时间,状态',
    scores: '成绩',
    exportSuccess: '导出成功',
    exportFailed: '导出失败',
    myClasses: '我的班级',
    myClassesDesc: '查看和管理您创建的班级',
    classCode: '群号',
    role: '角色',
    enterClass: '进入班级',
    noClasses: '暂无班级，去创建一个班级吧',
    loadClassesFailed: '加载班级列表失败',
    classOwner: '班级所有者',
    admin: '管理员',
    member: '普通成员',
    owner: '所有者',
    members: '名成员',
    classMembers: '班级成员',
    muted: '已禁言',
    enterMessage: '输入消息...',
    publish: '发布',
    publishExam: '发布考试',
    publishHomework: '发布作业（暂未开放）',
    publishNotice: '发布公告（暂未开放）',
    send: '发送',
    enterExam: '进入考试',
    viewExam: '查看考试',
    examDuration: '考试时长',
    minutes: '分钟',
    currentClass: '当前班级',
    publishSuccess: '发布成功',
    sendFailed: '发送失败',
    homeworkNotAvailable: '作业功能暂未开放',
    noticeNotAvailable: '公告功能暂未开放',
    student: '学生',
    submitTime: '提交时间',
    status: '状态',
    grade: '评分',
    viewPaper: '查看试卷',
    graded: '已评分',
    pendingGrade: '待评分',
    confirmGrade: '确定要评分吗？',
    gradingSuccess: '评分成功',
    myClasses: '我的班级',
    myClassesDesc: '管理班级，查看班级成员',
    classCode: '班级群号',
    classTeacher: '班主任',
    memberCount: '成员数量',
    joinClass: '加入班级',
    enterClassCode: '请输入班级群号',
    leaveClass: '退出班级',
    confirmLeave: '确定要退出班级吗？',
    joinedSuccess: '加入成功',
    leftSuccess: '退出成功',
    noClasses: '暂无班级',
    classInfo: '班级信息',
    classMembers: '班级成员',
    lastActivity: '最近活动',
    viewMember: '查看成员',
    member: '成员',
    role: '角色',
    joinedAt: '加入时间',
    kicked: '已移除',
    kickMember: '移除成员',
    confirmKick: '确定要移除该成员吗？',
    kickedSuccess: '已移除成员',
    createClass: '创建班级',
    className: '班级名称',
    enterClassName: '请输入班级名称',
    classCreated: '班级创建成功'
  },
  account: {
    basicInfo: '基本资料',
    editInfo: '编辑资料',
    realName: '姓名',
    username: '学号/工号',
    phone: '手机号',
    email: '邮箱',
    enterRealName: '请输入姓名',
    enterPhone: '请输入手机号',
    enterEmail: '请输入邮箱',
    save: '保存修改',
    reset: '重置',
    avatar: '我的头像',
    uploadAvatar: '上传新头像',
    avatarTip: '支持 JPG、PNG 格式，大小不超过 2MB',
    password: '密码管理',
    changePassword: '修改密码',
    oldPassword: '旧密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    enterOldPassword: '请输入旧密码',
    enterNewPassword: '请输入新密码',
    confirmNewPassword: '请确认新密码',
    or: '或者',
    forgotPassword: '忘记旧密码？通过手机验证重置',
    enterPhoneLastSix: '请输入手机号后六位',
    sendCode: '发送验证码',
    secondsResend: '秒后重发',
    verificationCode: '验证码',
    enterVerificationCode: '请输入验证码',
    verifyAndReset: '验证并重置密码',
    account: '账号管理'
  },
  classChat: {
    members: '名成员',
    startTime: '开始时间',
    endTime: '结束时间',
    duration: '时长',
    minutes: '分钟',
    enterExam: '进入考试',
    viewExam: '查看考试',
    enterMessage: '输入消息...',
    send: '发送',
    muted: '您已被禁言',
    classMembers: '班级成员',
    owner: '创建者',
    admin: '管理员',
    member: '成员'
  },
  admin: {
    userManagement: '用户管理',
    userManagementDesc: '管理系统用户，包括学生和教师账号',
    searchUsernameOrName: '搜索用户名或姓名',
    createUser: '新增用户',
    editUser: '编辑用户',
    username: '用户名',
    realName: '姓名',
    password: '密码',
    email: '邮箱',
    phone: '电话',
    normal: '正常',
    disabled: '禁用',
    enable: '启用',
    disable: '禁用',
    createTime: '创建时间',
    enterUsername: '请输入用户名',
    enterRealName: '请输入姓名',
    enterPassword: '请输入密码',
    leaveBlankNoChange: '留空则不修改',
    confirmDisable: '确定要禁用该用户吗？',
    confirmEnable: '确定要启用该用户吗？',
    confirmDeleteUser: '确定要删除该用户吗？',
    departmentManagement: '院系管理',
    departmentManagementDesc: '管理学校院系信息',
    departmentName: '院系名称',
    departmentCode: '院系代码',
    createDepartment: '创建院系',
    editDepartment: '编辑院系',
    searchDepartment: '搜索院系',
    enterDepartmentName: '请输入院系名称',
    confirmDeleteDepartment: '确定要删除该院系吗？',
    sortOrder: '排序',
    classManagement: '班级管理',
    classManagementDesc: '管理班级信息',
    className: '班级名称',
    classCode: '班级代码',
    department: '所属院系',
    createClass: '创建班级',
    editClass: '编辑班级',
    searchClass: '搜索班级',
    enterClassName: '请输入班级名称',
    selectDepartment: '请选择院系',
    confirmDeleteClass: '确定要删除该班级吗？',
    inviteCode: '群号',
    grade: '年级',
    enterGrade: '如：2021',
    systemStatistics: '数据统计',
    systemStatisticsDesc: '查看系统整体数据统计',
    totalUsers: '总用户数',
    totalStudents: '学生数',
    totalTeachers: '教师数',
    totalExams: '考试数',
    totalPapers: '试卷数',
    totalQuestions: '题目数',
    departmentCount: '院系数',
    participationCount: '参与人次',
    classCount: '班级数',
    userTypeDistribution: '用户类型分布',
    examStatusDistribution: '考试状态分布',
    monthlyExamStatistics: '月度考试统计',
    todayExams: '今日考试',
    activeUsers: '活跃用户',
    logManagement: '日志管理',
    logManagementDesc: '查看系统操作日志',
    systemLogs: '系统日志',
    systemLogsDesc: '查看系统操作记录',
    operation: '操作',
    operationDesc: '操作描述',
    operator: '操作用户',
    requestMethod: '请求方法',
    ipAddress: 'IP地址',
    operationTime: '操作时间',
    target: '操作对象',
    detail: '详情',
    searchOperation: '搜索操作',
    searchOperator: '搜索操作人',
    selectType: '选择类型',
    loginLog: '登录日志',
    operationLog: '操作日志',
    selectDateRange: '选择日期范围',
    viewLog: '查看日志'
  }
}

export const en = {
  common: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    save: 'Save',
    reset: 'Reset',
    back: 'Back',
    success: 'Success',
    failed: 'Failed',
    loading: 'Loading...',
    noData: 'No data',
    confirmDelete: 'Are you sure you want to delete?',
    tip: 'Tip',
    all: 'All',
    name: 'Name',
    code: 'Code',
    department: 'Department',
    class: 'Class',
    user: 'User',
    admin: 'Admin',
    teacher: 'Teacher',
    student: 'Student',
    role: 'Role',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    phone: 'Phone',
    realName: 'Real Name',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    notModifyLeaveEmpty: 'Leave empty to keep current',
    per: 'per',
    distribution: 'Distribution',
    remark: 'Remark',
    participation: 'Participations',
    exam: 'Exam',
    paper: 'Paper',
    question: 'Question',
    score: 'Score',
    time: 'Time',
    status: 'Status',
    statistics: 'Statistics',
    logs: 'Logs',
    overview: 'Overview',
    dashboard: 'Dashboard',
    account: 'Account',
    message: 'Message',
    language: 'Language',
    chinese: '中文',
    english: 'English',
    myClasses: 'My Classes',
    history: 'History',
    wrongQuestions: 'Wrong Questions',
    examList: 'Exam List',
    takeExam: 'Take Exam',
    viewDetail: 'View Detail',
    grade: 'Grade',
    monitor: 'Monitor',
    manage: 'Manage',
    subject: 'Subject',
    knowledgePoint: 'Knowledge Point',
    paperManage: 'Paper Manage',
    questionManage: 'Question Manage',
    subjectManage: 'Subject Manage',
    examManage: 'Exam Manage',
    examRecord: 'Exam Record',
    systemLog: 'System Log',
    userManage: 'User Manage',
    departmentManage: 'Department Manage',
    classManage: 'Class Manage',
    dataStatistics: 'Data Statistics',
    leftCount: 'Leave Count',
    maxLeaveCount: 'Max Leave Count',
    leaveDetection: 'Leave Detection',
    shuffleQuestions: 'Shuffle Questions',
    shuffleOptions: 'Shuffle Options',
    passRate: 'Pass Rate',
    viewAfterExam: 'View After Exam',
    duration: 'Duration (minutes)',
    startTime: 'Start Time',
    endTime: 'End Time',
    title: 'Title',
    content: 'Content',
    options: 'Options',
    correctAnswer: 'Correct Answer',
    type: 'Type',
    singleChoice: 'Single',
    multipleChoice: 'Multiple',
    trueFalse: 'True/False',
    fillBlank: 'Blank',
    shortAnswer: 'Essay',
    single: 'Single',
    multiple: 'Multiple',
    judgment: 'True/False',
    essay: 'Essay',
    detail: 'View Detail',
    pending: 'Pending',
    notStarted: 'Not Started',
    ongoing: 'Ongoing',
    finished: 'Finished',
    submitted: 'Submitted',
    notSubmitted: 'Not Submitted',
    autoSave: 'Auto Save',
    manualSave: 'Manual Save',
    submitExam: 'Submit Exam',
    timeRemaining: 'Time Remaining',
    seconds: 'seconds',
    minutes: 'minutes',
    hours: 'hours',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    total: 'Total',
    average: 'Average',
    count: 'Count',
    percent: 'Percent',
    date: 'Date',
    operation: 'Operation',
    method: 'Method',
    ip: 'IP Address',
    createTime: 'Create Time',
    updateTime: 'Update Time',
    inviteCode: 'Invite Code',
    members: 'Members',
    messages: 'Messages',
    send: 'Send',
    join: 'Join',
    leave: 'Leave',
    upload: 'Upload',
    avatar: 'Avatar',
    about: 'About',
    version: 'Version',
    copyright: 'Copyright',
    clearCache: 'Clear Cache',
    changePassword: 'Change Password',
    editProfile: 'Edit Profile',
    welcome: 'Welcome',
    recentExam: 'Recent Exams',
    upcomingExam: 'Upcoming Exams',
    completedExam: 'Completed Exams',
    examNotice: 'Exam Notice',
    logRecent: 'Recent Operations',
    viewMore: 'View More',
    noMore: 'No more',
    page: 'Page',
    of: 'of',
    goToPage: 'Go to page',
    rowsPerPage: 'Rows per page',
    prevPage: 'Previous',
    nextPage: 'Next',
    firstPage: 'First',
    lastPage: 'Last',
    loginSuccess: 'Login successful',
    registerSuccess: 'Register successful',
    passwordChanged: 'Password changed successfully',
    profileUpdated: 'Profile updated successfully',
    pleaseLogin: 'Please login first',
    sessionExpired: 'Session expired, please login again',
    networkError: 'Network error',
    serverError: 'Server error',
    notFound: 'Not found',
    forbidden: 'Access denied',
    examStarted: 'Exam has started',
    examFinished: 'Exam has finished',
    examNotStarted: 'Exam has not started',
    examSubmitted: 'Exam submitted',
    leaveWarning: 'Leave detected',
    exceedLeaveCount: 'Exceeded leave count, auto-submitted',
    leaveCount: 'Leave Count',
    pleaseAnswerAll: 'Please answer all questions before submitting',
    confirmSubmit: 'Are you sure you want to submit?',
    savedSuccessfully: 'Saved successfully',
    saveFailed: 'Save failed',
    loadingMore: 'Loading more...',
    enterExam: 'Enter Exam',
    viewPaper: 'View Paper',
    viewScore: 'View Score',
    viewAnalysis: 'View Analysis',
    practice: 'Practice',
    mastered: 'Mastered',
    notMastered: 'Not Mastered',
    correctRate: 'Correct Rate',
    correct: 'Correct',
    wrong: 'Wrong',
    difficulty: 'Difficulty',
    frequency: 'Error Frequency',
    publish: 'Publish',
    unpublish: 'Unpublish',
    start: 'Start',
    finish: 'Finish',
    extend: 'Extend',
    extendMinutes: 'Extend minutes',
    generate: 'Generate',
    import: 'Import',
    export: 'Export',
    copy: 'Copy',
    copied: 'Copied',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    invertSelect: 'Invert Selection',
    selectedCount: 'Selected {count} items',
    batchDelete: 'Batch Delete',
    batchOperation: 'Batch Operation',
    batchSuccess: 'Batch operation successful',
    batchFailed: 'Batch operation failed',
    selectDepartment: 'Select Department',
    selectSubject: 'Select Subject',
    selectQuestionType: 'Select Question Type',
    selectRole: 'Select Role',
    selectStatus: 'Select Status',
    selectDate: 'Select Date',
    startDate: 'Start Date',
    endDate: 'End Date',
    selectTime: 'Select Time',
    quickSelect: 'Quick Select',
    customRange: 'Custom Range',
    searchPlaceholder: 'Enter keyword',
    filterPlaceholder: 'Select filter',
    resetFilter: 'Reset Filter',
    applyFilter: 'Apply Filter',
    filterResult: '{count} results',
    sortAsc: 'Ascending',
    sortDesc: 'Descending',
    sortBy: 'Sort by',
    sortByName: 'Sort by name',
    sortByTime: 'Sort by time',
    sortByCount: 'Sort by count',
    sortByScore: 'Sort by score',
    ascending: 'Ascending',
    descending: 'Descending',
    show: 'Show',
    hide: 'Hide',
    expand: 'Expand',
    collapse: 'Collapse',
    toggle: 'Toggle',
    enable: 'Enable',
    disable: 'Disable',
    switch: 'Switch',
    on: 'On',
    off: 'Off',
    yes: 'Yes',
    no: 'No',
    unknown: 'Unknown',
    other: 'Other',
    pleaseWait: 'Please wait',
    processing: 'Processing...',
    complete: 'Complete',
    confirmLogout: 'Are you sure you want to logout?',
    examCreatedSuccess: 'Exam created successfully',
    examUpdatedSuccess: 'Exam updated successfully',
    examDeletedSuccess: 'Exam deleted successfully',
    examPublishedSuccess: 'Exam published successfully',
    examUnpublishedSuccess: 'Exam unpublished',
    paperCreatedSuccess: 'Paper created successfully',
    paperUpdatedSuccess: 'Paper updated successfully',
    paperDeletedSuccess: 'Paper deleted successfully',
    questionCreatedSuccess: 'Question created successfully',
    questionUpdatedSuccess: 'Question updated successfully',
    questionDeletedSuccess: 'Question deleted successfully',
    subjectCreatedSuccess: 'Subject created successfully',
    subjectUpdatedSuccess: 'Subject updated successfully',
    subjectDeletedSuccess: 'Subject deleted successfully',
    userCreatedSuccess: 'User created successfully',
    userUpdatedSuccess: 'User updated successfully',
    userDeletedSuccess: 'User deleted successfully',
    departmentCreatedSuccess: 'Department created successfully',
    departmentUpdatedSuccess: 'Department updated successfully',
    departmentDeletedSuccess: 'Department deleted successfully',
    classCreatedSuccess: 'Class created successfully',
    classUpdatedSuccess: 'Class updated successfully',
    classDeletedSuccess: 'Class deleted successfully',
    joinedClassSuccess: 'Joined class successfully',
    leftClassSuccess: 'Left class successfully',
    messageSentSuccess: 'Message sent successfully',
    examSubmittedSuccess: 'Exam submitted successfully',
    examGradedSuccess: 'Grading successful',
    statisticsUpdated: 'Statistics updated',
    logsCleared: 'Logs cleared',
    cacheCleared: 'Cache cleared',
    welcomeBack: 'Welcome back',
    hello: 'Hello',
    goodbye: 'Goodbye',
    haveANiceDay: 'Have a nice day',
    seeYouLater: 'See you later',
    goodLuck: 'Good luck',
    congratulations: 'Congratulations',
    wellDone: 'Well done',
    excellent: 'Excellent',
    greatJob: 'Great job',
    niceWork: 'Nice work',
    thankYou: 'Thank you',
    statusPending: 'Pending',
    statusOngoing: 'Ongoing',
    statusFinished: 'Finished',
    systemManagement: 'System Management',
    userManagement: 'User Management',
    departmentManagement: 'Department Management',
    classManagement: 'Class Management',
    dataStatistics: 'Data Statistics',
    systemLogs: 'System Logs',
    recentLogs: 'Recent Operation Logs',
    recentExams: 'Recent Exams',
    manageExams: 'Manage Exams',
    upcomingExams: 'Upcoming Exams',
    allExams: 'All Exams',
    waiting: 'Waiting',
    noUpcomingExams: 'No upcoming exams',
    examTips: 'Exam Tips',
    subjectManagement: 'Subject Management',
    questionManagement: 'Question Management',
    paperManagement: 'Paper Management',
    examManagement: 'Exam Management',
    scoreAnalysis: 'Score Analysis',
    allDepartments: 'All Departments',
    noLogData: 'No log data',
    totalRecords: 'Total {total} records',
    year: 'y',
    month: 'm',
    day: 'd',
    saving: 'Saving...',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Save failed',
    creator: 'Creator',
    unknownUser: 'Unknown',
    classMembers: 'Class Members',
    muted: 'Muted',
    sendFailed: 'Send failed',
    enterMessage: 'Enter message...',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    createUser: 'Create User',
    updateUser: 'Update User',
    deleteUser: 'Delete User',
    createDepartment: 'Create Department',
    updateDepartment: 'Update Department',
    deleteDepartment: 'Delete Department',
    createClass: 'Create Class',
    updateClass: 'Update Class',
    deleteClass: 'Delete Class',
    createExam: 'Create Exam',
    updateExam: 'Update Exam',
    deleteExam: 'Delete Exam',
    editExam: 'Edit Exam',
    basicInfo: 'Basic Information',
    id: 'ID',
    viewAnswer: 'View Answer',
    allExams: 'All Exams',
    questionCount: 'Question Count',
    judgment: 'True/False',
    essay: 'Short Answer',
    inviteMembers: 'Invite Members',
    importText: 'Import Text',
    formatDesc: 'Format Description',
    importNote: 'Import Note',
    target: 'Target',
    shuffleQuestions: 'Shuffle Questions',
    shuffleOptions: 'Shuffle Options',
    leaveDetection: 'Leave Detection',
    passRate: 'Pass Rate',
    allowViewAfterExam: 'Allow View After Exam',
    examDuration: 'Duration (minutes)',
    selectPaper: 'Select Paper',
    selectClass: 'Select Class',
    startDate: 'Start Date',
    startTime: 'Start Time',
    examSettings: 'Exam Settings',
    selectStartTime: 'Select start time',
    publishExam: 'Publish Exam',
    inviteMembers: 'Invite Members'
  },
  login: {
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: 'Enter password',
    student: 'Student',
    teacher: 'Teacher',
    admin: 'Admin',

    welcome: 'Welcome back',
    selectRole: 'Please select your role',
    studentUsername: 'Enter student username',
    teacherUsername: 'Enter teacher username',
    adminUsername: 'Enter admin username',
    adminAccount: 'Enter admin account',
    goRegister: 'Register',
    backToStudentTeacher: 'Back to Student/Teacher',
    createAccount: 'Create Account',
    registerInfo: 'Select role and fill registration information',
    confirmPassword: 'Confirm password',
    selectDepartment: 'Select department',
    goLogin: 'Login',
    slogan: 'Professional online exam system, making learning more efficient',
    feature1: 'Rich question type support',
    feature2: 'Smart anti-cheating mechanism',
    feature3: 'Auto grading system',
    feature4: 'Comprehensive data analysis',
    passwordNotMatch: 'Passwords do not match',
    usernameLength: 'Username must be 3-20 characters',
    passwordLength: 'Password must be 6-20 characters',
    studentNotFound: 'Student account not found',
    teacherNotFound: 'Teacher account not found',
    adminNotFound: 'Admin account not found'
  },
  dashboard: {
    welcome: 'Welcome back',
    totalUsers: 'Total Users',
    count: 'Count',
    departmentCount: 'Department Count',
    classCount: 'Class Count',
    paperCount: 'Paper Count',
    questionCount: 'Question Count',
    examCount: 'Exam Count',
    pendingExams: 'Pending Exams',
    completedExams: 'Completed',
    wrongCount: 'Wrong Count',
    averageScore: 'Average Score',
    scoreUnit: 'pts',
    myClasses: 'My Classes',
    examList: 'Exam List',
    examHistory: 'Exam History',
    systemManagement: 'System Management',
    userManagement: 'User Management',
    departmentManagement: 'Department Management',
    classManagement: 'Class Management',
    dataStatistics: 'Data Statistics',
    systemLogs: 'System Logs',
    recentLogs: 'Recent Operation Logs',
    recentExams: 'Recent Exams',
    manageExams: 'Manage Exams',
    upcomingExams: 'Upcoming Exams',
    allExams: 'All Exams',
    enterExam: 'Enter Exam',
    waiting: 'Waiting',
    noUpcomingExams: 'No upcoming exams',
    examTips: 'Exam Tips',
    tip1: 'Keep network stable during exam',
    tip2: 'Do not switch pages frequently during exam',
    tip3: 'Answers auto-save, but manual submission is recommended',
    tip4: 'View wrong answer analysis after exam',
    subjectManagement: 'Subject Management',
    questionManagement: 'Question Management',
    paperManagement: 'Paper Management',
    examManagement: 'Exam Management',
    minutes: 'mins',
    scoreAnalysis: 'Score Analysis'
  },
  student: {
    viewLatest: 'View latest class updates',
    viewAndJoin: 'View and join upcoming exams',
    searchExam: 'Search exam name',
    viewExamHistory: 'View completed exam results and details',
    submitTime: 'Submit Time',
    autoSubmitted: 'Auto Submitted',
    viewAnalysis: 'View your learning data analysis',
    subjectScores: 'Subject Scores',
    timesExam: ' exams',
    answerStats: 'Answer Statistics',
    correctCount: 'Correct Answers',
    wrongCount: 'Wrong Answers',
    skippedCount: 'Skipped Answers',
    scoreTrend: 'Score Trend',
    knowledgeMastery: 'Knowledge Mastery',
    totalExams: 'Total Exams',
    averageScore: 'Average Score',
    highestScore: 'Highest Score',
    wrongBookDesc: 'Automatically collects all wrong answers, supports repeated practice',
    notMastered: 'Not Mastered',
    mastered: 'Mastered',
    questionContent: 'Question Content',
    passRate: 'Pass Rate',
    practiceCount: 'Practice Count',
    viewAnswer: 'View Answer',
    practice: 'Practice',
    markNotMastered: 'Mark as Not Mastered',
    markMastered: 'Mark as Mastered',
    wrongAnswer: 'Wrong Answer',
    notRecorded: 'Not Recorded',
    analysis: 'Analysis',
    wrongPractice: 'Wrong Question Practice',
    enterAnswer: 'Enter your answer',
    answerCorrect: 'Correct Answer',
    answerWrong: 'Wrong Answer',
    nextQuestion: 'Next Question',
    prevQuestion: 'Previous Question',
    examInProgress: 'In Progress',
    submitExam: 'Submit',
    questionNav: 'Question Navigation',
    current: 'Current',
    answered: 'Answered',
    unanswered: 'Unanswered',
    exam: 'Exam',
    score: 'Score',
    scored: 'Scored',
    pendingGrade: 'Pending Grading',
    save: 'Save',
    questionUnit: ' questions',
    paperLocked: 'Teacher has disabled post-exam paper viewing, cannot view paper content',
    question: 'Question',
    yourAnswer: 'Your Answer',
    loading: 'Loading...',
    warning: 'Warning',
    leftExam: 'You have left the exam page!',
    leaveCount: 'Leave Count',
    remainingChances: 'Remaining',
    chancesLeft: ' chances, exceeding will auto-submit',
    reachedLimit: 'Limit reached, will auto-submit soon',
    continueExam: 'Continue Exam',
    loadingExam: 'Loading exam information...',
    classChat: {
      members: ' members',
      startTime: 'Start Time',
      endTime: 'End Time',
      duration: 'Duration',
      minutes: ' mins',
      enterExam: 'Enter Exam',
      viewExam: 'View Exam',
      enterMessage: 'Enter message...',
      send: 'Send',
      muted: 'You are muted',
      classMembers: 'Class Members',
      owner: 'Owner',
      admin: 'Admin',
      member: 'Member'
    },
    selectSubject: 'Select Subject',
    selectStatus: 'Select Status',
    search: 'Search',
    operation: 'Operation',
    type: 'Type',
    status: 'Status',
    close: 'Close',
    submit: 'Submit',
    correct: 'Correct',
    wrong: 'Wrong',
    correctAnswer: 'Correct Answer',
    single: 'Single',
    multiple: 'Multiple',
    judgment: 'True/False',
    fillBlank: 'Blank',
    essay: 'Essay',
    programming: 'Code',
    account: {
      basicInfo: 'Basic Information',
      realName: 'Name',
      username: 'Student/Employee ID',
      phone: 'Phone',
      email: 'Email',
      enterRealName: 'Enter name',
      enterPhone: 'Enter phone number',
      enterEmail: 'Enter email',
      save: 'Save Changes',
      reset: 'Reset',
      avatar: 'My Avatar',
      uploadAvatar: 'Upload New Avatar',
      avatarTip: 'Supports JPG, PNG format, max 2MB',
      password: 'Password Management',
      changePassword: 'Change Password',
      oldPassword: 'Old Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      enterOldPassword: 'Enter old password',
      enterNewPassword: 'Enter new password',
      confirmNewPassword: 'Confirm new password',
      or: 'Or',
      forgotPassword: 'Forgot password? Reset via phone verification',
      enterPhoneLastSix: 'Enter last 6 digits of phone',
      sendCode: 'Send Verification Code',
      secondsResend: 's resend',
      verificationCode: 'Verification Code',
      enterVerificationCode: 'Enter verification code',
      verifyAndReset: 'Verify and Reset Password',
      account: 'Account Management'
    },
    enterClassCode: 'Enter class code',
    joinClass: 'Join Class',
    noClass: 'No classes yet, enter class code to join',
    loadFailed: 'Failed to load class list',
    joinSuccess: 'Joined class successfully',
    joinFailed: 'Failed to join class',
    owner: 'Owner',
    member: 'Member',
    examStarted: 'Exam started',
    examPublished: 'Exam published',
    justNow: 'Just now',
    ago: 'ago',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    examList: 'Exam List',
    examHistory: 'Exam History',
    wrongQuestions: 'Wrong Questions',
    statistics: 'Statistics',
    account: 'Account',
    noExams: 'No exams',
    noHistory: 'No exam records',
    noWrongQuestions: 'No wrong questions',
    viewPaper: 'View Paper',
    viewScore: 'View Score',
    viewAnalysis: 'View Analysis',
    practice: 'Practice',
    mastered: 'Mastered',
    notMastered: 'Not Mastered',
    correctRate: 'Correct Rate',
    frequency: 'Wrong Frequency',
    totalScore: 'Total Score',
    passScore: 'Pass Score',
    duration: 'Duration',
    startTime: 'Start Time',
    endTime: 'End Time',
    status: 'Status',
    score: 'Score',
    rank: 'Rank',
    average: 'Average',
    highest: 'Highest',
    lowest: 'Lowest',
    subject: 'Subject',
    questionType: 'Question Type',
    answer: 'Answer',
    correctAnswer: 'Correct Answer',
    yourAnswer: 'Your Answer',
    analysis: 'Analysis',
    myClasses: 'My Classes',
    classChat: 'Class Chat',
    sendMessage: 'Send Message',
    noMessages: 'No messages',
    examNotice: 'Exam Notice',
    examEnded: 'Exam Ended',
    enterExam: 'Enter Exam',
    takeExam: 'Take Exam',
    submitExam: 'Submit Exam',
    timeRemaining: 'Time Remaining',
    autoSave: 'Auto Save',
    confirmSubmit: 'Are you sure you want to submit?',
    pleaseAnswerAll: 'Please answer all questions before submitting',
    examSubmitted: 'Submitted',
    notSubmitted: 'Not Submitted',
    pending: 'Pending',
    ongoing: 'Ongoing',
    finished: 'Finished',
    wrongCount: 'Wrong Count',
    completedCount: 'Completed Count',
    pendingCount: 'Pending Count',
    scoreTrend: 'Score Trend',
    subjectAnalysis: 'Subject Analysis',
    questionAnalysis: 'Question Analysis',
    personalBest: 'Personal Best',
    improvement: 'Improvement',
    needImprovement: 'Needs Improvement',
    studySuggestion: 'Study Suggestions',
    recentExam: 'Recent Exam',
    upcomingExam: 'Upcoming Exam',
    classInfo: 'Class Info',
    classMembers: 'Class Members',
    classActivities: 'Class Activities',
    leaveClass: 'Leave Class',
    confirmLeave: 'Are you sure you want to leave?',
    joinedSuccess: 'Joined successfully',
    leftSuccess: 'Left successfully',
    classCode: 'Class Code',
    classTeacher: 'Class Teacher',
    memberCount: 'Member Count',
    lastActivity: 'Last Activity',
    activityType: 'Activity Type',
    examCreated: 'Exam Created',
    examPublished: 'Exam Published',
    examFinished: 'Exam Finished',
    messageSent: 'Message Sent',
    memberJoined: 'Member Joined',
    memberLeft: 'Member Left',
    examName: 'Exam Name',
    examDate: 'Exam Date',
    examDuration: 'Exam Duration',
    examScore: 'Exam Score',
    examRank: 'Exam Rank',
    viewDetails: 'View Details',
    retry: 'Retry',
    markMastered: 'Mark as Mastered',
    markNotMastered: 'Unmark as Mastered',
    filterSubject: 'Filter by Subject',
    filterMastery: 'Filter by Mastery',
    allSubjects: 'All Subjects',
    allStatus: 'All Status',
    statisticsOverview: 'Statistics Overview',
    learningProgress: 'Learning Progress',
    knowledgePoints: 'Knowledge Points',
    masteredCount: 'Mastered',
    notMasteredCount: 'Not Mastered',
    totalQuestions: 'Total Questions',
    accuracyRate: 'Accuracy Rate',
    weakPoints: 'Weak Points',
    strongPoints: 'Strong Points',
    studyPlan: 'Study Plan',
    recommendedQuestions: 'Recommended Questions',
    dailyGoal: 'Daily Goal',
    completedToday: 'Completed Today',
    streak: 'Streak',
    achievements: 'Achievements',
    totalExams: 'Total Exams',
    highestScore: 'Highest Score',
    perfectScore: 'Perfect Scores',
    studyTime: 'Study Time',
    questionsAnswered: 'Questions Answered',
    correctAnswers: 'Correct Answers',
    accuracy: 'Accuracy',
    improvementRate: 'Improvement Rate',
    globalRank: 'Global Rank',
    classRank: 'Class Rank',
    schoolRank: 'School Rank',
    shareResult: 'Share Result',
    downloadReport: 'Download Report',
    printReport: 'Print Report',
    exportData: 'Export Data',
    importData: 'Import Data',
    settings: 'Settings',
    notificationSettings: 'Notification Settings',
    soundSettings: 'Sound Settings',
    appearanceSettings: 'Appearance Settings',
    languageSettings: 'Language Settings',
    privacySettings: 'Privacy Settings',
    about: 'About',
    version: 'Version',
    feedback: 'Feedback',
    help: 'Help',
    contactUs: 'Contact Us',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    copyright: 'Copyright'
  },
  teacher: {
    viewLatest: 'View latest class updates',
    examManagement: 'Exam Management',
    examManagementDesc: 'Publish and manage exams, monitor examinee status',
    selectSubject: 'Select subject',
    searchExamTitle: 'Search exam title',
    selectExam: 'Select Exam',
    publishExam: 'Publish Exam',
    id: 'ID',
    examTitle: 'Exam Title',
    totalScore: 'Total Score',
    monitor: 'Monitor',
    extend: 'Extend',
    stats: 'Stats',
    editExam: 'Edit Exam',
    selectPaper: 'Select paper',
    selectClass: 'Select class',
    selectAtLeastOneClass: 'Please select at least one class',
    selectPublishClass: 'Select publish class',
    selectStartTime: 'Select start time',
    selectEndTime: 'Select end time',
    examDuration: 'Exam Duration',
    antiCheatSettings: 'Anti-cheat Settings',
    maxLeaveCount: 'Max leave count',
    exceedAutoSubmit: 'times, exceeding will auto-submit',
    postExamSettings: 'Post-exam Settings',
    allowViewAfterExam: 'Allow view paper after exam',
    viewAfterExamDesc: 'After enabling, students can view paper and score upon submission',
    default60: 'Default 60',
    shuffleQuestionsDesc: 'Questions will be randomly ordered',
    shuffleOptionsDesc: 'Options will be randomly ordered',
    leaveDetectionDesc: 'Detect leaving the exam page',
    maxLeaveCountDesc: 'Auto-submit after exceeding count',
    allowViewAfterExamDesc: 'View paper and answers after exam',
    saveChanges: 'Save Changes',
    enterExamTitle: 'Enter exam title',
    getExamInfoFailed: 'Failed to get exam info',
    publishSuccess: 'Published successfully',
    confirmStartExam: 'Are you sure you want to start this exam?',
    examStarted: 'Exam started',
    confirmFinishExam: 'Are you sure you want to finish this exam? All unsubmitted students will be auto-submitted',
    examFinished: 'Exam finished',
    enterExtendMinutes: 'Enter extension time (minutes)',
    extendExamTime: 'Extend Exam Time',
    extendSuccess: 'Exam time extended',
    examMonitor: 'Exam Monitor',
    totalStudents: 'Total Students',
    submitted: 'Submitted',
    autoSubmitted: 'Auto Submitted',
    suspicious: 'Suspicious',
    score: 'Score',
    notStarted: 'Not Started',
    examStats: 'Exam Statistics',
    avgScore: 'Average Score',
    maxScore: 'Highest Score',
    minScore: 'Lowest Score',
    classChat: {
      members: ' members',
      startTime: 'Start Time',
      endTime: 'End Time',
      duration: 'Duration',
      minutes: 'mins',
      enterExam: 'Enter Exam',
      viewExam: 'View Exam',
      enterMessage: 'Enter message...',
      send: 'Send',
      muted: 'You are muted',
      classMembers: 'Class Members',
      owner: 'Owner',
      admin: 'Admin',
      member: 'Member'
    },
    paperManagement: 'Paper Management',
    paperManagementDesc: 'Create and manage exam papers, support manual and auto generation',
    paperTitle: 'Paper Title',
    questionCount: 'Question Count',
    publish: 'Publish',
    unpublish: 'Unpublish',
    createPaper: 'Create Paper',
    editPaper: 'Edit Paper',
    selectSubjectHint: 'Select subject',
    enterPaperTitle: 'Enter paper title',
    passScore: 'Pass Score',
    paperDuration: 'Duration(mins)',
    duration: 'Duration',
    addQuestion: 'Add Question',
    questionType: 'Question Type',
    questionContent: 'Question Content',
    options: 'Options',
    correctAnswer: 'Correct Answer',
    scoreHint: 'Score',
    analysis: 'Analysis',
    selectQuestionType: 'Select question type',
    singleChoice: 'Single',
    multipleChoice: 'Multiple',
    judgment: 'True/False',
    fillBlank: 'Blank',
    essay: 'Essay',
    programming: 'Code',
    paperPublished: 'Paper published',
    paperUnpublished: 'Paper unpublished',
    paperCreated: 'Paper created successfully',
    paperUpdated: 'Paper updated successfully',
    confirmUnpublish: 'Are you sure you want to unpublish this paper?',
    confirmPublish: 'Are you sure you want to publish this paper?',
    confirmDelete: 'Are you sure you want to delete this paper?',
    draft: 'Draft',
    published: 'Published',
    searchPaperTitle: 'Search paper title',
    autoGenerate: 'Auto Generate',
    preview: 'Preview',
    questionSettings: 'Question Settings',
    searchQuestion: 'Search question',
    clearSelection: 'Clear Selection',
    currentSubject: 'Current Subject',
    batchSetScore: 'Batch Set Score',
    applyToSelected: 'Apply to Selected',
    setScore: 'Set Score',
    selected: 'Selected',
    questions: 'questions',
    scoreUnit: 'pts',
    selectSubjectFirst: 'Please select subject first to add questions',
    autoCalculate: 'Auto calculate',
    enterDuration: 'Enter exam duration',
    enterPassRate: 'Enter pass rate percentage',
    questionCountScore: 'Question Count & Score',
    count: 'Count',
    perQuestion: 'Per question',
    generateTip1: 'System will randomly select specified number of questions from question bank',
    generateTip2: 'If question bank has insufficient questions for certain type, generation will fail',
    generatePaper: 'Generate Paper',
    generateResult: 'Generation Result',
    studentPreview: 'Student Preview',
    current: 'Current',
    unanswered: 'Unanswered',
    question: 'Question',
    prevQuestion: 'Previous',
    nextQuestion: 'Next',
    noQuestion: 'No questions',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    enterScore: 'Enter score',
    batchSetSuccess: 'Batch setting successful',
    selectAtLeastOneQuestion: 'Please select at least one question',
    selectAtLeastOneQuestionType: 'Please select at least one question type',
    getPaperInfoFailed: 'Failed to get paper info',
    enterAnswer: 'Enter answer',
    questionManagement: 'Question Management',
    questionManagementDesc: 'Manage exam questions, support multiple question types',
    keyword: 'Keyword',
    batchDelete: 'Batch Delete',
    importQuestions: 'Import Questions',
    exportQuestions: 'Export Questions',
    viewQuestion: 'View Question',
    subject: 'Subject',
    content: 'Content',
    operation: 'Operation',
    difficulty: 'Difficulty',
    frequency: 'Usage Count',
    correctRate: 'Correct Rate',
    enterContent: 'Enter question content',
    enterOptions: 'Enter options (JSON format)',
    enterAnswer: 'Enter answer',
    enterAnalysis: 'Enter analysis',
    questionCreated: 'Question created successfully',
    questionUpdated: 'Question updated successfully',
    questionDeleted: 'Question deleted successfully',
    confirmDeleteQuestion: 'Are you sure you want to delete this question?',
    confirmBatchDelete: 'Are you sure you want to delete selected questions?',
    addQuestion: 'Add Question',
    editQuestion: 'Edit Question',
    batchImport: 'Batch Import',
    searchQuestion: 'Search question',
    optionCount: 'Option Count',
    optionUnit: ' options',
    enterOption: 'Enter option ',
    correctAnswer: 'Correct Answer',
    referenceAnswer: 'Reference Answer',
    fillBlankPlaceholder: 'Enter question content, use $blank$ for blank positions',
    insertBlank: 'Insert Blank Marker',
    blankHint: 'Click to insert "$blank$" at cursor position as blank marker',
    fillBlankAnswerPlaceholder: 'Multiple blanks separated by commas, e.g., answer1,answer2,answer3',
    questionText: 'Question Text',
    importPlaceholder: 'Paste question text, supports following formats:\n\n1. Single Choice:\n1. Question content\nA. Option 1\nB. Option 2\nC. Option 3\nD. Option 4\nAnswer: B\n\n2. Multiple Choice:\n2. Question content (Multiple)\nA. Option 1\nB. Option 2\nC. Option 3\nD. Option 4\nAnswer: A,B\n\n3. True/False:\n3. Question content (True)\nor\n3. Question content (False)\n\n4. Fill Blank:\n4. Question content (Answer: xxx)\n\n5. Essay:\n5. Question content\n(Reference Answer: xxx)',
    formatInstructions: 'Format Instructions',
    questionNumbering: 'Question Numbering',
    numberingFormat: 'Supports formats like "1.", "一、", "（一）"',
    optionFormat: 'Option Format',
    optionFormatDesc: 'Starts with "A.", "B.", "C.", "D."',
    answerMark: 'Answer Marker',
    answerMarkDesc: 'Write "Answer: A" or "Answer: A,B" on a separate line',
    judgmentFormat: 'True/False',
    judgmentFormatDesc: 'Add "(True)" or "(False)" at the end of question',
    fillBlankFormat: 'Fill Blank',
    fillBlankFormatDesc: 'Use "(Answer: xxx)" or "[Answer xxx]"',
    essayFormat: 'Essay',
    essayFormatDesc: 'Use "(Reference Answer: xxx)"',
    startImport: 'Start Import',
    importResult: 'Import Result',
    success: 'Success',
    failed: 'Failed',
    failedDetails: 'Failed Details',
    enterQuestionText: 'Enter question text',
    importFailed: 'Import failed',
    importFailedRetry: 'Import failed, please try again later',
    correct: 'Correct',
    incorrect: 'Incorrect',
    subjectManagement: 'Subject Management',
    subjectManagementDesc: 'Manage exam subjects',
    subjectName: 'Subject Name',
    subjectCode: 'Subject Code',
    description: 'Description',
    createSubject: 'Create Subject',
    editSubject: 'Edit Subject',
    searchSubject: 'Search subject',
    enterSubjectName: 'Enter subject name',
    enterSubjectCode: 'Enter subject code',
    enterDescription: 'Enter description',
    confirmDeleteSubject: 'Are you sure you want to delete this subject?',
    subjectCreated: 'Subject created successfully',
    subjectUpdated: 'Subject updated successfully',
    subjectDeleted: 'Subject deleted successfully',
    examRecordManagement: 'Grading & Score Management',
    examRecordManagementDesc: 'View exam score statistics, analyze wrong questions',
    examName: 'Exam Name',
    exportScores: 'Export Scores',
    scoreStatistics: 'Score Statistics',
    highestScore: 'Highest Score',
    lowestScore: 'Lowest Score',
    averageScore: 'Average Score',
    passRate: 'Pass Rate',
    totalStudents: 'Total Students',
    passCount: 'Pass Count',
    wrongQuestionAnalysis: 'Wrong Question Analysis',
    questionId: 'Question ID',
    questionContent: 'Question Content',
    questionType: 'Question Type',
    score: 'Score',
    totalAnswered: 'Answered Count',
    correctCount: 'Correct Count',
    studentScoreList: 'Student Score List',
    studentName: 'Student Name',
    screenSwitchCount: 'Screen Switches',
    suspicious: 'Suspicious',
    startTime: 'Start Time',
    submitTime: 'Submit Time',
    detailInDevelopment: 'Detail view feature in development',
    csvHeader: 'Student ID,Score,Submit Time,Status',
    scores: 'Scores',
    exportSuccess: 'Export successful',
    exportFailed: 'Export failed',
    myClasses: 'My Classes',
    myClassesDesc: 'View and manage your classes',
    classCode: 'Class Code',
    role: 'Role',
    enterClass: 'Enter Class',
    noClasses: 'No classes yet, create one now',
    loadClassesFailed: 'Failed to load class list',
    classOwner: 'Class Owner',
    admin: 'Admin',
    member: 'Member',
    owner: 'Owner',
    members: 'members',
    classMembers: 'Class Members',
    muted: 'Muted',
    enterMessage: 'Enter message...',
    publish: 'Publish',
    publishExam: 'Publish Exam',
    publishHomework: 'Publish Homework (Coming Soon)',
    publishNotice: 'Publish Notice (Coming Soon)',
    send: 'Send',
    enterExam: 'Enter Exam',
    viewExam: 'View Exam',
    examDuration: 'Exam Duration',
    minutes: ' mins',
    currentClass: 'Current Class',
    publishSuccess: 'Published successfully',
    sendFailed: 'Send failed',
    homeworkNotAvailable: 'Homework feature coming soon',
    noticeNotAvailable: 'Notice feature coming soon',
    student: 'Student',
    submitTime: 'Submit Time',
    status: 'Status',
    grade: 'Grade',
    viewPaper: 'View Paper',
    graded: 'Graded',
    pendingGrade: 'Pending Grading',
    confirmGrade: 'Are you sure you want to grade?',
    gradingSuccess: 'Grading successful',
    myClasses: 'My Classes',
    myClassesDesc: 'Manage classes, view class members',
    classCode: 'Class Code',
    classTeacher: 'Class Teacher',
    memberCount: 'Member Count',
    joinClass: 'Join Class',
    enterClassCode: 'Enter class code',
    leaveClass: 'Leave Class',
    confirmLeave: 'Are you sure you want to leave this class?',
    joinedSuccess: 'Joined successfully',
    leftSuccess: 'Left successfully',
    noClasses: 'No classes yet',
    classInfo: 'Class Info',
    classMembers: 'Class Members',
    lastActivity: 'Last Activity',
    viewMember: 'View Member',
    member: 'Member',
    role: 'Role',
    joinedAt: 'Joined At',
    kicked: 'Removed',
    kickMember: 'Remove Member',
    confirmKick: 'Are you sure you want to remove this member?',
    kickedSuccess: 'Member removed',
    createClass: 'Create Class',
    className: 'Class Name',
    enterClassName: 'Enter class name',
    classCreated: 'Class created successfully'
  },
  account: {
    basicInfo: 'Basic Information',
    editInfo: 'Edit Profile',
    realName: 'Name',
    username: 'Student/Staff ID',
    phone: 'Phone',
    email: 'Email',
    enterRealName: 'Enter name',
    enterPhone: 'Enter phone number',
    enterEmail: 'Enter email',
    save: 'Save Changes',
    reset: 'Reset',
    avatar: 'My Avatar',
    uploadAvatar: 'Upload New Avatar',
    avatarTip: 'Supports JPG, PNG formats, max 2MB',
    password: 'Password Management',
    changePassword: 'Change Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    enterOldPassword: 'Enter old password',
    enterNewPassword: 'Enter new password',
    confirmNewPassword: 'Confirm new password',
    or: 'Or',
    forgotPassword: 'Forgot password? Reset via phone verification',
    enterPhoneLastSix: 'Enter last 6 digits of phone',
    sendCode: 'Send Verification Code',
    secondsResend: 'seconds to resend',
    verificationCode: 'Verification Code',
    enterVerificationCode: 'Enter verification code',
    verifyAndReset: 'Verify and Reset',
    account: 'Account Management'
  },
  classChat: {
    members: ' members',
    startTime: 'Start Time',
    endTime: 'End Time',
    duration: 'Duration',
    minutes: ' mins',
    enterExam: 'Enter Exam',
    viewExam: 'View Exam',
    enterMessage: 'Enter message...',
    send: 'Send',
    muted: 'You are muted',
    classMembers: 'Class Members',
    owner: 'Owner',
    admin: 'Admin',
    member: 'Member'
  },
  admin: {
    userManagement: 'User Management',
    userManagementDesc: 'Manage system users, including students and teachers',
    searchUsernameOrName: 'Search username or name',
    createUser: 'Create User',
    editUser: 'Edit User',
    username: 'Username',
    realName: 'Real Name',
    password: 'Password',
    email: 'Email',
    phone: 'Phone',
    normal: 'Normal',
    disabled: 'Disabled',
    enable: 'Enable',
    disable: 'Disable',
    createTime: 'Create Time',
    enterUsername: 'Enter username',
    enterRealName: 'Enter real name',
    enterPassword: 'Enter password',
    leaveBlankNoChange: 'Leave blank to keep current',
    confirmDisable: 'Are you sure you want to disable this user?',
    confirmEnable: 'Are you sure you want to enable this user?',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    departmentManagement: 'Department Management',
    departmentManagementDesc: 'Manage school department information',
    departmentName: 'Department Name',
    departmentCode: 'Department Code',
    createDepartment: 'Create Department',
    editDepartment: 'Edit Department',
    searchDepartment: 'Search department',
    enterDepartmentName: 'Enter department name',
    confirmDeleteDepartment: 'Are you sure you want to delete this department?',
    sortOrder: 'Sort Order',
    classManagement: 'Class Management',
    classManagementDesc: 'Manage class information',
    className: 'Class Name',
    classCode: 'Class Code',
    department: 'Department',
    createClass: 'Create Class',
    editClass: 'Edit Class',
    searchClass: 'Search class',
    enterClassName: 'Enter class name',
    selectDepartment: 'Select department',
    confirmDeleteClass: 'Are you sure you want to delete this class?',
    inviteCode: 'Invite Code',
    grade: 'Grade',
    enterGrade: 'e.g., 2021',
    systemStatistics: 'Statistics',
    systemStatisticsDesc: 'View overall system data statistics',
    totalUsers: 'Total Users',
    totalStudents: 'Students',
    totalTeachers: 'Teachers',
    totalExams: 'Exams',
    totalPapers: 'Papers',
    totalQuestions: 'Questions',
    departmentCount: 'Departments',
    participationCount: 'Participations',
    classCount: 'Classes',
    userTypeDistribution: 'User Type Distribution',
    examStatusDistribution: 'Exam Status Distribution',
    monthlyExamStatistics: 'Monthly Exam Statistics',
    todayExams: "Today's Exams",
    activeUsers: 'Active Users',
    logManagement: 'Log Management',
    logManagementDesc: 'View system operation logs',
    systemLogs: 'System Logs',
    systemLogsDesc: 'View system operation records',
    operation: 'Operation',
    operationDesc: 'Operation Description',
    operator: 'Operator',
    requestMethod: 'Request Method',
    ipAddress: 'IP Address',
    operationTime: 'Operation Time',
    target: 'Target',
    detail: 'Detail',
    searchOperation: 'Search operation',
    searchOperator: 'Search operator',
    selectType: 'Select type',
    loginLog: 'Login Log',
    operationLog: 'Operation Log',
    selectDateRange: 'Select date range',
    viewLog: 'View Log'
  }
}

export const useLang = () => {
  const getLanguage = () => {
    try {
      return localStorage.getItem('language') || 'zh'
    } catch (e) {
      return 'zh'
    }
  }

  const setLanguage = (lang) => {
    localStorage.setItem('language', lang)
  }

  const t = (key, lang = getLanguage()) => {
    const messages = lang === 'zh' ? zh : en
    const keys = key.split('.')
    let result = messages
    for (const k of keys) {
      if (result && typeof result === 'object') {
        result = result[k]
      } else {
        return key
      }
    }
    return result || key
  }

  return { t, getLanguage, setLanguage }
}