import { ref } from 'vue'

export const zh = {
  common: {
    home: '首页',
    login: '登录',
    register: '注册',
    logout: '退出登录',
    submit: '提交',
    cancel: '取消',
    confirm: '确定',
    delete: '删除',
    edit: '编辑',
    add: '新增',
    search: '搜索',
    save: '保存',
    reset: '重置',
    back: '返回',
    success: '操作成功',
    failed: '操作失败',
    loading: '加载中...',
    noData: '暂无数据',
    confirmDelete: '确定要删除吗？',
    confirmDeleteSubject: '确定要删除 {name} 吗？',
    confirmFinish: '确定要结束考试吗？',
    confirmStart: '确定要开始考试吗？',
    confirmDeleteUser: '确定要删除用户 {username} 吗？',
    tip: '提示',
    warning: '警告',
    loginFailed: '登录失败',
    close: '关闭',
    deleteSuccess: '删除成功',
    deleteFailed: '删除失败',
    updateSuccess: '修改成功',
    createSuccess: '创建成功',
    submitting: '提交中...',
    pleaseSelectRole: '请选择角色',
    all: '全部',
    name: '名称',
    code: '代码',
    department: '院系',
    class: '班级',
    user: '用户',
    admin: '管理员',
    teacher: '教师',
    student: '学生',
    owner: '所有者',
    member: '成员',
    role: '角色',
    username: '用户名',
    password: '密码',
    email: '邮箱',
    phone: '手机号',
    realName: '真实姓名',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    pleaseEnter: '请输入',
    pleaseSelect: '请选择',
    notModifyLeaveEmpty: '不修改请留空',
    per: '每',
    distribution: '分布',
    remark: '备注',
    participation: '参与人次',
    exam: '考试',
    paper: '试卷',
    question: '题目',
    score: '分数',
    time: '时间',
    status: '状态',
    statistics: '统计',
    logs: '日志',
    overview: '概览',
    view: '查看',
    dashboard: '首页',
    account: '个人中心',
    message: '消息',
    language: '语言',
    chinese: '中文',
    english: 'English',
    myClasses: '我的班级',
    myClass: '我的班级',
    classChat: '班级聊天',
    history: '考试历史',
    wrongQuestions: '错题本',
    examList: '考试列表',
    takeExam: '开始考试',
    examTake: '考试',
    viewDetail: '查看详情',
    grade: '评分',
    monitor: '监控',
    examMonitor: '考试监控',
    examStatistics: '考试统计',
    examineeStatus: '考生状态',
    totalPeople: '总人数',
    submitted: '已提交',
    notStarted: '未开始',
    ongoing: '进行中',
    autoSubmitted: '强制收卷',
    pending: '待开始',
    finished: '已结束',
    durationMinutes: '分钟',
    start: '开始',
    studentId: '学号',
    submitTime: '提交时间',
    unknownSubject: '未知科目',
    manage: '管理',
    subject: '科目',
    knowledgePoint: '知识点',
    paperManage: '试卷管理',
    paperPreview: '试卷预览',
    questionManage: '题库管理',
    subjectManage: '科目管理',
    examManage: '考试管理',
    examRecord: '考试记录',
    examRecords: '考试记录',
    examRecordDetail: '考试记录详情',
    viewRecords: '查看记录',
    examDetail: '试卷详情',
    systemLog: '系统日志',
    logManage: '日志管理',
    userManage: '用户管理',
    departmentManage: '院系管理',
    classManage: '班级管理',
    dataStatistics: '数据统计',
    allSubjects: '全部科目',
    allStatus: '全部状态',
    prevQuestion: '上一题',
    nextQuestion: '下一题',
    questionNav: '答题卡',
    createAndManage: '创建和管理试卷',
    createPaper: '创建试卷',
    editPaper: '编辑试卷',
    paperTitle: '试卷标题',
    paperDesc: '试卷描述',
    selectSubjectFirst: '请选择科目',
    examDuration: '考试时长',
    questionList: '题目列表',
    noQuestions: '暂无题目，请添加题目',
    confirmAdd: '确认添加',
    questionTypeLabel: '题目类型',
    selectQuestionTypeFirst: '请选择题目类型',
    publishAndManage: '发布和管理考试',
    publishExam: '发布考试',
    published: '已发布',
    draft: '草稿',
    totalScore: '总分',
    passScore: '及格分',
    preview: '预览',
    questionType: '题型',
    questionContent: '题目内容',
    addQuestion: '添加题目',
    editQuestion: '编辑题目',
    selectSubject: '选择科目',
    selectQuestionType: '选择题型',
    enterQuestionContent: '请输入题目内容',
    batchImport: '批量导入',
    leftCount: '离开次数',
    maxLeaveCount: '最大离开次数',
    leaveDetection: '离开检测',
    shuffleQuestions: '题目乱序',
    shuffleOptions: '选项乱序',
    passRate: '及格比例',
    viewAfterExam: '考后查看',
    duration: '时长(分钟)',
    startTime: '开始时间',
    endTime: '结束时间',
    title: '标题',
    content: '内容',
    options: '选项',
    option: '选项',
    addOption: '添加选项',
    correctAnswer: '正确答案',
    enterCorrectAnswer: '请输入正确答案',
    enterScore: '请输入分值',
    studentAnswer: '学生答案',
    referenceAnswer: '参考答案',
    notAnswered: '未作答',
    current: '当前',
    unanswered: '未答',
    total: '共',
    type: '类型',
    singleChoice: '单选题',
    multipleChoice: '多选题',
    trueFalse: '判断题',
    fillBlank: '填空题',
    shortAnswer: '简答题',
    pending: '待开始',
    ongoing: '进行中',
    finished: '已结束',
    submitted: '已提交',
    notSubmitted: '未提交',
    autoSave: '自动保存',
    manualSave: '手动保存',
    submitExam: '提交考试',
    timeRemaining: '剩余时间',
    seconds: '秒',
    minutes: '分钟',
    hours: '小时',
    today: '今天',
    yesterday: '昨天',
    thisWeek: '本周',
    thisMonth: '本月',
    total: '总计',
    average: '平均',
    count: '数量',
    percent: '百分比',
    date: '日期',
    operation: '操作',
    method: '方法',
    ip: 'IP地址',
    createTime: '创建时间',
    updateTime: '更新时间',
    inviteCode: '邀请码',
    shareInviteCode: '分享邀请码给同学加入班级',
    viewLatest: '查看班级最新动态',
    members: '成员',
    messages: '消息',
    send: '发送',
    join: '加入',
    leave: '离开',
    upload: '上传',
    avatar: '头像',
    about: '关于',
    version: '版本',
    copyright: '版权所有',
    clearCache: '清除缓存',
    changePassword: '修改密码',
    editProfile: '编辑资料',
    welcome: '欢迎',
    recentExam: '最近考试',
    upcomingExam: '待考考试',
    completedExam: '已完成考试',
    examNotice: '考试须知',
    logRecent: '最近操作',
    viewMore: '查看更多',
    noMore: '没有更多了',
    noMoreData: '没有更多数据',
    page: '页',
    of: '共',
    goToPage: '跳转到',
    rowsPerPage: '每页条数',
    prevPage: '上一页',
    nextPage: '下一页',
    firstPage: '首页',
    lastPage: '末页',
    loginSuccess: '登录成功',
    registerSuccess: '注册成功',
    passwordChanged: '密码修改成功',
    profileUpdated: '资料更新成功',
    pleaseLogin: '请先登录',
    sessionExpired: '登录已过期，请重新登录',
    networkError: '网络错误',
    serverError: '服务器错误',
    notFound: '未找到',
    forbidden: '无权访问',
    examStarted: '考试已开始',
    examFinished: '考试已结束',
    examNotStarted: '考试尚未开始',
    examSubmitted: '已提交试卷',
    leaveWarning: '检测到离开考试页面',
    exceedLeaveCount: '离开次数过多，已自动交卷',
    pleaseAnswerAll: '请完成所有题目后再提交',
    confirmSubmit: '确定要提交试卷吗？',
    questions: '题',
    savedSuccessfully: '保存成功',
    saveFailed: '保存失败',
    loadingMore: '加载更多...',
    pullDownRefresh: '下拉刷新',
    releaseRefresh: '松开刷新',
    refreshing: '刷新中...',
    enterExam: '进入考试',
    viewPaper: '查看试卷',
    viewScore: '查看成绩',
    viewAnalysis: '查看分析',
    scoreAnalysis: '成绩分析',
    scored: '已评分',
    currentScore: '当前得分',
    correct: '正确',
    wrong: '错误',
    submitGrade: '提交评分',
    practice: '练习',
    mastered: '已掌握',
    notMastered: '未掌握',
    correctRate: '正确率',
    difficulty: '难度',
    frequency: '错误次数',
    publish: '发布',
    unpublish: '取消发布',
    start: '开始',
    finish: '结束',
    extend: '延长',
    extendMinutes: '延长分钟数',
    generate: '生成',
    import: '导入',
    export: '导出',
    copy: '复制',
    copied: '已复制',
    copySuccess: '复制成功',
    selectAll: '全选',
    deselectAll: '取消全选',
    invertSelect: '反选',
    selectedCount: '已选 {count} 项',
    batchDelete: '批量删除',
    batchOperation: '批量操作',
    batchSuccess: '批量操作成功',
    batchFailed: '批量操作失败',
    selectDepartment: '选择院系',
    selectSubject: '选择科目',
    selectQuestionType: '选择题型',
    selectRole: '选择角色',
    selectStatus: '选择状态',
    selectDate: '选择日期',
    startDate: '开始日期',
    endDate: '结束日期',
    selectTime: '选择时间',
    quickSelect: '快捷选择',
    customRange: '自定义范围',
    searchPlaceholder: '请输入关键词',
    filterPlaceholder: '请选择筛选条件',
    resetFilter: '重置筛选',
    applyFilter: '应用筛选',
    filterResult: '共 {count} 条结果',
    sortAsc: '升序',
    sortDesc: '降序',
    sortBy: '排序方式',
    sortByName: '按名称排序',
    sortByTime: '按时间排序',
    sortByCount: '按数量排序',
    sortByScore: '按分数排序',
    ascending: '升序',
    descending: '降序',
    show: '显示',
    hide: '隐藏',
    expand: '展开',
    collapse: '折叠',
    toggle: '切换',
    enable: '启用',
    disable: '禁用',
    switch: '开关',
    on: '开',
    off: '关',
    yes: '是',
    no: '否',
    unknown: '未知',
    other: '其他',
    pleaseWait: '请稍候',
    processing: '处理中...',
    complete: '完成',
    cancelProcess: '取消',
    confirmCancel: '确定要取消吗？',
    hasChanges: '有未保存的更改，确定要离开吗？',
    unsavedChanges: '未保存的更改',
    discardChanges: '放弃更改',
    saveChanges: '保存更改',
    confirmLogout: '确定要退出登录吗？',
    confirmClearCache: '确定要清除缓存吗？所有本地数据将被删除。',
    aboutSystem: '关于系统',
    systemName: '在线考试系统',
    systemDescription: '一个基于Vue + Spring Boot的在线考试系统',
    developer: '开发者',
    techStack: '技术栈',
    contact: '联系方式',
    feedback: '意见反馈',
    help: '帮助',
    documentation: '文档',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    agreement: '用户协议',
    iAgree: '我同意',
    readAgreement: '已阅读并同意',
    mustAgree: '必须同意协议才能继续',
    validateFailed: '验证失败',
    validateSuccess: '验证成功',
    checkInput: '请检查输入',
    inputError: '输入有误',
    inputTooShort: '输入内容太短',
    inputTooLong: '输入内容太长',
    inputInvalid: '输入格式不正确',
    passwordNotMatch: '两次输入的密码不一致',
    passwordTooWeak: '密码强度不够',
    passwordChangedSuccess: '密码修改成功，请重新登录',
    profileUpdatedSuccess: '个人资料更新成功',
    avatarUpdatedSuccess: '头像更新成功',
    examCreatedSuccess: '考试创建成功',
    examUpdatedSuccess: '考试更新成功',
    examDeletedSuccess: '考试删除成功',
    examPublishedSuccess: '考试发布成功',
    examUnpublishedSuccess: '考试已取消发布',
    publishedSuccess: '发布成功',
    examExtendedSuccess: '考试时间已延长',
    paperCreatedSuccess: '试卷创建成功',
    paperUpdatedSuccess: '试卷更新成功',
    paperDeletedSuccess: '试卷删除成功',
    questionCreatedSuccess: '题目创建成功',
    questionUpdatedSuccess: '题目更新成功',
    questionDeletedSuccess: '题目删除成功',
    questionImportedSuccess: '题目导入成功',
    subjectCreatedSuccess: '科目创建成功',
    subjectUpdatedSuccess: '科目更新成功',
    subjectDeletedSuccess: '科目删除成功',
    userCreatedSuccess: '用户创建成功',
    userUpdatedSuccess: '用户更新成功',
    userDeletedSuccess: '用户删除成功',
    departmentCreatedSuccess: '院系创建成功',
    departmentUpdatedSuccess: '院系更新成功',
    departmentDeletedSuccess: '院系删除成功',
    classCreatedSuccess: '班级创建成功',
    classUpdatedSuccess: '班级更新成功',
    classDeletedSuccess: '班级删除成功',
    joinedClassSuccess: '加入班级成功',
    leftClassSuccess: '退出班级成功',
    messageSentSuccess: '消息发送成功',
    examStartedSuccess: '考试开始成功',
    examFinishedSuccess: '考试结束成功',
    examSubmittedSuccess: '考试提交成功',
    examGradedSuccess: '评分成功',
    wrongQuestionCreated: '错题记录已创建',
    wrongQuestionUpdated: '错题记录已更新',
    wrongQuestionDeleted: '错题记录已删除',
    statisticsUpdated: '统计数据已更新',
    logsCleared: '日志已清空',
    cacheCleared: '缓存已清除',
    networkTimeout: '网络请求超时',
    connectionFailed: '连接失败',
    serviceUnavailable: '服务不可用',
    maintenance: '系统维护中',
    upgrade: '系统升级中',
    comingSoon: '即将上线',
    underDevelopment: '开发中',
    featureNotAvailable: '功能暂不可用',
    permissionDenied: '权限不足',
    needAdmin: '需要管理员权限',
    needTeacher: '需要教师权限',
    needStudent: '需要学生权限',
    notInClass: '未加入班级',
    classFull: '班级已满',
    inviteCodeInvalid: '邀请码无效',
    inviteCodeExpired: '邀请码已过期',
    alreadyInClass: '已加入该班级',
    examNotFound: '考试不存在',
    paperNotFound: '试卷不存在',
    questionNotFound: '题目不存在',
    userNotFound: '用户不存在',
    departmentNotFound: '院系不存在',
    classNotFound: '班级不存在',
    subjectNotFound: '科目不存在',
    recordNotFound: '记录不存在',
    logNotFound: '日志不存在',
    wrongQuestionNotFound: '错题不存在',
    cannotDelete: '无法删除',
    cannotDeleteSelf: '不能删除自己',
    cannotDeleteAdmin: '不能删除管理员',
    cannotUpdate: '无法更新',
    cannotCreate: '无法创建',
    hasChildren: '存在子项，无法删除',
    inUse: '正在使用中，无法删除',
    examInProgress: '考试进行中，无法修改',
    examFinishedCannotEdit: '考试已结束，无法修改',
    paperInUse: '试卷正在被使用，无法删除',
    questionInUse: '题目正在被使用，无法删除',
    subjectInUse: '科目正在被使用，无法删除',
    departmentInUse: '院系正在被使用，无法删除',
    classInUse: '班级正在被使用，无法删除',
    userInUse: '用户正在被使用，无法删除',
    pleaseFillAll: '请填写所有必填项',
    pleaseFillRequired: '请填写必填项',
    pleaseSelectRequired: '请选择必填项',
    pleaseUploadRequired: '请上传必填文件',
    formatNotSupported: '格式不支持',
    fileTooLarge: '文件过大',
    fileTooSmall: '文件过小',
    uploadFailed: '上传失败',
    uploadSuccess: '上传成功',
    downloading: '下载中...',
    downloadSuccess: '下载成功',
    downloadFailed: '下载失败',
    exporting: '导出中...',
    exportSuccess: '导出成功',
    exportFailed: '导出失败',
    importing: '导入中...',
    importSuccess: '导入成功',
    importFailed: '导入失败',
    generating: '生成中...',
    generateSuccess: '生成成功',
    generateFailed: '生成失败',
    analyzing: '分析中...',
    analysisSuccess: '分析成功',
    analysisFailed: '分析失败',
    calculating: '计算中...',
    calculationSuccess: '计算成功',
    calculationFailed: '计算失败',
    synchronizing: '同步中...',
    syncSuccess: '同步成功',
    syncFailed: '同步失败',
    refreshingData: '刷新数据中...',
    refreshSuccess: '刷新成功',
    refreshFailed: '刷新失败',
    loadingData: '加载数据中...',
    loadSuccess: '加载成功',
    loadFailed: '加载失败',
    savingData: '保存数据中...',
    submittingData: '提交数据中...',
    deletingData: '删除数据中...',
    updatingData: '更新数据中...',
    creatingData: '创建数据中...',
    processingData: '处理数据中...',
    validatingData: '验证数据中...',
    dataValidated: '数据验证通过',
    dataValidationFailed: '数据验证失败',
    dataFormatError: '数据格式错误',
    dataMissing: '数据缺失',
    dataDuplicate: '数据重复',
    dataConflict: '数据冲突',
    dataOutOfRange: '数据超出范围',
    dataNotAllowed: '数据不允许',
    dataInvalid: '数据无效',
    connectionEstablished: '连接已建立',
    connectionLost: '连接已断开',
    reconnecting: '重新连接中...',
    reconnected: '重新连接成功',
    reconnectFailed: '重新连接失败',
    offlineMode: '离线模式',
    onlineMode: '在线模式',
    autoReconnect: '自动重连',
    manualReconnect: '手动重连',
    checkNetwork: '请检查网络连接',
    checkServer: '请检查服务器状态',
    checkInternet: '请检查网络连接',
    tryAgainLater: '请稍后重试',
    contactSupport: '请联系技术支持',
    errorOccurred: '发生错误',
    unknownError: '未知错误',
    unexpectedError: '意外错误',
    systemError: '系统错误',
    applicationError: '应用程序错误',
    databaseError: '数据库错误',
    authenticationError: '认证错误',
    authorizationError: '授权错误',
    configurationError: '配置错误',
    initializationError: '初始化错误',
    runtimeError: '运行时错误',
    validationError: '验证错误',
    businessError: '业务错误',
    networkErrorRetry: '网络错误，请重试',
    serverErrorRetry: '服务器错误，请重试',
    timeoutRetry: '请求超时，请重试',
    retry: '重试',
    retryLater: '稍后重试',
    skip: '跳过',
    ignore: '忽略',
    continue: '继续',
    abort: '中止',
    retryCount: '重试次数: {count}',
    maxRetryReached: '已达到最大重试次数',
    pleaseTryAgain: '请重试',
    pleaseContactAdmin: '请联系管理员',
    pleaseCheckLogs: '请查看日志',
    pleaseReportIssue: '请报告问题',
    thankYou: '谢谢',
    welcomeBack: '欢迎回来',
    hello: '你好',
    goodbye: '再见',
    haveANiceDay: '祝你愉快',
    seeYouLater: '再见',
    goodLuck: '祝你好运',
    congratulations: '恭喜',
    wellDone: '做得好',
    excellent: '太棒了',
    greatJob: '干得好',
    niceWork: '做得不错',
    thankYouForYourFeedback: '感谢你的反馈',
    weValueYourFeedback: '我们重视你的反馈',
    yourOpinionMatters: '你的意见很重要',
    pleaseShareYourThoughts: '请分享你的想法',
    helpUsImprove: '帮助我们改进',
    stayTuned: '敬请期待',
    comingSoonMessage: '即将推出更多精彩功能',
    newFeatures: '新功能',
    improvedFeatures: '改进功能',
    bugFixes: '修复问题',
    performanceImprovements: '性能优化',
    securityUpdates: '安全更新',
    stabilityImprovements: '稳定性改进',
    userExperience: '用户体验',
    interfaceImprovements: '界面改进',
    accessibilityImprovements: '无障碍改进',
    internationalization: '国际化',
    localization: '本地化',
    multiLanguage: '多语言支持',
    responsiveDesign: '响应式设计',
    mobileOptimization: '移动端优化',
    tabletOptimization: '平板端优化',
    desktopOptimization: '桌面端优化',
    crossPlatform: '跨平台支持',
    offlineSupport: '离线支持',
    realTime: '实时同步',
    cloudSync: '云同步',
    dataBackup: '数据备份',
    dataRecovery: '数据恢复',
    dataExport: '数据导出',
    dataImport: '数据导入',
    dataMigration: '数据迁移',
    dataIntegration: '数据集成',
    apiIntegration: 'API集成',
    thirdPartyIntegration: '第三方集成',
    pluginSupport: '插件支持',
    extensibility: '可扩展性',
    customization: '可定制性',
    flexibility: '灵活性',
    scalability: '可扩展性',
    reliability: '可靠性',
    availability: '可用性',
    performance: '性能',
    security: '安全性',
    privacy: '隐私',
    compliance: '合规性',
    standards: '标准',
    bestPractices: '最佳实践',
    documentation: '文档',
    support: '支持',
    community: '社区',
    openSource: '开源',
    contribution: '贡献',
    license: '许可证',
    copyrightYear: '2024',
    allRightsReserved: '保留所有权利',
    madeWithLove: '用爱制作',
    poweredBy: '由 {name} 提供支持',
    builtWith: '使用 {name} 构建',
    versionInfo: '版本 {version}',
    buildNumber: '构建号 {build}',
    buildDate: '构建日期 {date}',
    environment: '环境: {env}',
    debugMode: '调试模式',
    productionMode: '生产模式',
    developmentMode: '开发模式',
    stagingMode: '预发布模式',
    testMode: '测试模式',

    maintenanceMode: '维护模式',
    readOnlyMode: '只读模式',
    safeMode: '安全模式',
    emergencyMode: '紧急模式',
    recoveryMode: '恢复模式',
    setupMode: '设置模式',
    wizardMode: '向导模式',
    tutorialMode: '教程模式',
    beginnerMode: '初学者模式',
    advancedMode: '高级模式',
    expertMode: '专家模式',
    adminMode: '管理员模式',
    guestMode: '访客模式',
    anonymousMode: '匿名模式',
    authenticatedMode: '认证模式',
    authorizedMode: '授权模式',
    restrictedMode: '受限模式',
    lockedMode: '锁定模式',
    unlockedMode: '解锁模式',
    activeMode: '活动模式',
    inactiveMode: '非活动模式',
    suspendedMode: '暂停模式',
    resumedMode: '恢复模式',
    terminatedMode: '终止模式',
    completedMode: '完成模式',
    pendingMode: '待处理模式',
    processingMode: '处理中模式',
    failedMode: '失败模式',
    successMode: '成功模式',
    warningMode: '警告模式',
    errorMode: '错误模式',
    infoMode: '信息模式',
    debugModeLabel: '调试',
    traceMode: '跟踪',
    verboseMode: '详细',
    quietMode: '安静',
    silentMode: '静默',
    normalMode: '正常',
    strictMode: '严格',
    relaxedMode: '宽松',
    lenientMode: '宽容',
    strictValidation: '严格验证',
    relaxedValidation: '宽松验证',
    lenientValidation: '宽容验证',
    strictParsing: '严格解析',
    relaxedParsing: '宽松解析',
    lenientParsing: '宽容解析',
    strictFormatting: '严格格式化',
    relaxedFormatting: '宽松格式化',
    lenientFormatting: '宽容格式化',
    strictChecking: '严格检查',
    relaxedChecking: '宽松检查',
    lenientChecking: '宽容检查',
    strictModeEnabled: '严格模式已启用',
    relaxedModeEnabled: '宽松模式已启用',
    lenientModeEnabled: '宽容模式已启用',
    strictModeDisabled: '严格模式已禁用',
    relaxedModeDisabled: '宽松模式已禁用',
    lenientModeDisabled: '宽容模式已禁用',
    enableStrictMode: '启用严格模式',
    disableStrictMode: '禁用严格模式',
    toggleStrictMode: '切换严格模式',
    currentMode: '当前模式',
    modeChanged: '模式已更改',
    modeChangeFailed: '模式更改失败',
    cannotChangeMode: '无法更改模式',
    modeNotAvailable: '模式不可用',
    modeRestricted: '模式受限制',
    modeLocked: '模式已锁定',
    modeUnlocked: '模式已解锁',
    modeActivated: '模式已激活',
    modeDeactivated: '模式已停用',
    modeSuspended: '模式已暂停',
    modeResumed: '模式已恢复',
    modeTerminated: '模式已终止',
    modeCompleted: '模式已完成',
    modePending: '模式待处理',
    modeProcessing: '模式处理中',
    modeFailed: '模式失败',
    modeSuccess: '模式成功',
    modeWarning: '模式警告',
    modeError: '模式错误',
    modeInfo: '模式信息',
    modeDebug: '模式调试',
    modeTrace: '模式跟踪',
    modeVerbose: '模式详细',
    modeQuiet: '模式安静',
    modeSilent: '模式静默',
    modeNormal: '模式正常',
    languageChanged: '语言已更改',
    languageChangeFailed: '语言更改失败',
    cannotChangeLanguage: '无法更改语言',
    languageNotAvailable: '语言不可用',
    languageRestricted: '语言受限制',
    languageLocked: '语言已锁定',
    languageUnlocked: '语言已解锁',
    languageActivated: '语言已激活',
    languageDeactivated: '语言已停用',
    languageSuspended: '语言已暂停',
    languageResumed: '语言已恢复',
    languageTerminated: '语言已终止',
    languageCompleted: '语言已完成',
    languagePending: '语言待处理',
    languageProcessing: '语言处理中',
    languageFailed: '语言失败',
    languageSuccess: '语言成功',
    languageWarning: '语言警告',
    languageError: '语言错误',
    languageInfo: '语言信息',
    languageDebug: '语言调试',
    languageTrace: '语言跟踪',
    languageVerbose: '语言详细',
    languageQuiet: '语言安静',
    languageSilent: '语言静默',
    languageNormal: '语言正常',
    statusPending: '待开始',
    statusOngoing: '进行中',
    statusFinished: '已结束',
    allDepartments: '全部院系',
    noLogData: '暂无日志数据',
    totalRecords: '共 {total} 条记录',
    year: '年',
    month: '月',
    day: '日',
    saving: '保存中...',
    saveSuccess: '保存成功',
    saveFailed: '保存失败',
    creator: '创建者',
    unknownUser: '未知用户',
    classMembers: '班级成员',
    muted: '已禁言',
    sendFailed: '发送失败',
    enterMessage: '输入消息...',
    justNow: '刚刚',
    minutesAgo: '分钟前',
    hoursAgo: '小时前',
    classMessage: '班级消息',
    systemNotification: '系统通知',
    noClassMessage: '暂无班级消息',
    noSystemNotification: '暂无系统通知',
    noMessage: '暂无消息',
    startExam: '开始考试',
    publishNotice: '发布通知',
    createUser: '创建用户',
    updateUser: '更新用户',
    deleteUser: '删除用户',
    createDepartment: '创建院系',
    updateDepartment: '更新院系',
    deleteDepartment: '删除院系',
    createClass: '创建班级',
    updateClass: '更新班级',
    deleteClass: '删除班级',
    createExam: '创建考试',
    updateExam: '更新考试',
    deleteExam: '删除考试',
    editExam: '编辑考试',
    createExam: '创建考试',
    basicInfo: '基本信息',
    viewAnswer: '查看答案',
    allExams: '全部考试',
    questionCount: '题目数量',
    judgment: '判断题',
    essay: '简答题',
    inviteMembers: '邀请成员',
    importText: '导入文本',
    formatDesc: '格式说明',
    importNote: '导入注意事项',
    pasteQuestionText: '请粘贴题目文本',
    target: '目标',
    create: '创建'
  },
  teacher: {
    enterClassName: '输入班级名称',
    createClass: '创建班级',
    noClasses: '暂无班级，创建您的第一个班级吧',
    examTitle: '考试标题',
    enterExamTitle: '请输入考试标题',
    selectPaper: '选择试卷',
    selectClass: '选择班级',
    examDuration: '考试时长（分钟）',
    duration: '考试时长',
    enterDuration: '请输入考试时长',
    startDate: '开始日期',
    selectDate: '请选择日期',
    startTime: '开始时间',
    selectTime: '请选择时间',
    examSettings: '考试设置',
    passRate: '及格比例',
    default60: '默认60',
    shuffleQuestions: '题目乱序',
    shuffleQuestionsDesc: '开启后题目顺序随机排列',
    shuffleOptions: '选项乱序',
    shuffleOptionsDesc: '开启后选项顺序随机排列',
    leaveDetection: '离开检测',
    leaveDetectionDesc: '检测考试期间离开页面',
    maxLeaveCount: '离开次数上限',
    maxLeaveCountDesc: '超过此次数将自动收卷',
    allowViewAfterExam: '允许考后查看',
    allowViewAfterExamDesc: '考试结束后可查看试卷和答案',
    selectStartTime: '请选择开始时间',
    publishExam: '发布考试',
    inviteMembers: '邀请成员',
    grading: '评分中...',
    pleaseGradeAtLeastOne: '请至少给一道题评分',
    gradeSuccess: '评分成功',
    gradeFailed: '评分失败',
    questionSettings: '题目设置',
    searchQuestion: '搜索题目',
    clearSelection: '清空选择',
    currentSubject: '当前科目',
    batchSetScore: '批量设置分值',
    selectQuestionType: '选择题型',
    scoreHint: '分值',
    applyToSelected: '应用到已选',
    selected: '已选',
    setScore: '设置分值',
    selectAtLeastOneQuestion: '请至少选择一道题目',
    selectSubjectFirst: '请先选择科目',
    subjectNotFound: '关联科目不存在，请重新选择',
    batchSetSuccess: '批量设置成功',
    easy: '简单',
    medium: '中等',
    hard: '困难',
    singleChoice: '单选题',
    multipleChoice: '多选题',
    judgment: '判断题',
    fillBlank: '填空题',
    essay: '简答题',
    programming: '编程题',
    paperManagement: '试卷管理',
    paperManagementDesc: '创建和管理试卷',
    autoGenerate: '自动组卷',
    createPaper: '创建试卷',
    editPaper: '编辑试卷',
    paperTitle: '试卷标题',
    enterPaperTitle: '请输入试卷标题',
    totalScore: '总分',
    passScore: '及格分',
    paperDuration: '考试时长',
    minutes: '分钟',
    preview: '预览',
    publish: '发布',
    confirmPublish: '确定要发布试卷吗？',
    paperPublished: '试卷发布成功',
    confirmDelete: '确定要删除吗？',
    autoCalculate: '自动计算',
    enterDuration: '请输入时长',
    enterPassRate: '请输入及格比例',
    questionCountScore: '题目数量与分值',
    count: '数量',
    perQuestion: '每题',
    scoreUnit: '分',
    generateTip1: '系统将根据您设置的题目数量随机抽取题目生成试卷',
    generateTip2: '请确保各题型的题目数量不超过题库中该题型的题目总数',
    generatePaper: '生成试卷',
    generateResult: '生成结果',
    viewPaper: '查看试卷',
    getPaperInfoFailed: '获取试卷信息失败',
    selectSubject: '选择科目',
    selectQuestionTypeFirst: '请选择题型',
    enterScore: '请输入分值'
  },
  admin: {
    allDepartments: '全部院系'
  },
  login: {
    usernamePlaceholder: '请输入用户名',
    passwordPlaceholder: '请输入密码',
    student: '学生',
    teacher: '教师',
    admin: '管理员',
    studentNotFound: '学生账号不存在',
    teacherNotFound: '教师账号不存在',
    adminNotFound: '管理员账号不存在',
    loginFailed: '登录失败',
    enterUsernamePassword: '请输入账号和密码'
  },
  register: {
    title: '创建账号',
    subtitle: '选择身份并填写注册信息',
    confirmPasswordPlaceholder: '请确认密码',
    selectDepartment: '请选择学院',
    haveAccount: '已有账号？去登录',
    usernameLength: '用户名长度应为3-20个字符',
    passwordLength: '密码长度应为6-20个字符',
    passwordMismatch: '两次输入密码不一致',
    registerSuccess: '注册成功',
    registerFailed: '注册失败'
  },
  dashboard: {
    welcome: '欢迎回来',
    totalUsers: '总用户数',
    count: '数',
    departmentCount: '院系数',
    classCount: '班级数',
    paperCount: '试卷数',
    questionCount: '题目数',
    examCount: '考试数',
    pendingExams: '待考考试',
    completedExams: '已完成',
    wrongCount: '错题数',
    averageScore: '平均分',
    scoreUnit: '分',
    myClasses: '我的班级',
    myClass: '我的班级',
    examList: '考试列表',
    examHistory: '考试历史',
    systemManagement: '系统管理',
    userManagement: '用户管理',
    departmentManagement: '院系管理',
    classManagement: '班级管理',
    dataStatistics: '数据统计',
    systemLogs: '系统日志',
    recentLogs: '最近操作日志',
    recentExams: '最近考试',
    manageExams: '管理考试',
    upcomingExams: '待考考试',
    allExams: '全部考试',
    enterExam: '进入考试',
    waiting: '等待开始',
    noUpcomingExams: '暂无待考考试',
    scoreAnalysis: '成绩分析',
    examTips: '考试须知',
    tip1: '进入考试后请保持网络畅通',
    tip2: '考试过程中请勿频繁切换页面',
    tip3: '答案会自动保存，但建议手动提交',
    tip4: '考试结束后可查看错题分析',
    subjectManagement: '科目管理',
    questionManagement: '题库管理',
    paperManagement: '试卷管理',
    examManagement: '考试管理',
    minutes: '分钟'
  },
  student: {
    loadingExam: '加载考试中...',
    viewLatest: '查看班级最新动态',
    enterClassCode: '请输入班级群号',
    joinClass: '加入班级',
    noClass: '暂无班级，输入群号加入班级吧',
    joinSuccess: '加入班级成功',
    joinFailed: '加入班级失败',
    loadFailed: '加载班级列表失败',
    pleaseLogin: '请先登录',
    networkError: '网络错误',
    owner: '创建者',
    admin: '管理员',
    member: '成员',
    justNow: '刚刚',
    minutesAgo: '分钟前',
    hoursAgo: '小时前',
    ago: '前',
    examStarted: '开始考试',
    examPublished: '发布通知',
    viewAndJoin: '查看和参加考试',
    searchExam: '搜索考试名称',
    noExams: '暂无考试',
    autoSubmitted: '强制收卷',
    enterExam: '进入考试',
    waiting: '等待开始',
    viewDetail: '查看详情',
    examInProgress: '考试进行中',
    submitExam: '提交考试',
    examNotice: '考试须知',
    timeRemaining: '剩余时间',
    submitSuccess: '提交成功',
    submitFailed: '提交失败',
    confirmSubmit: '确定要提交试卷吗？',
    viewExamHistory: '查看考试历史',
    noHistory: '暂无考试记录',
    submitTime: '交卷时间',
    viewAnalysis: '查看成绩分析',
    totalExams: '总考试数',
    avgScore: '平均分',
    passRate: '通过率',
    subjectScores: '科目成绩',
    exams: '次考试',
    answerStats: '答题情况',
    correctCount: '答对题数',
    wrongCount: '答错题数',
    skippedCount: '未答题数',
    wrongBookDesc: '复习错题，巩固知识',
    allSubjects: '全部科目',
    allStatus: '全部状态',
    notMastered: '未学会',
    mastered: '已学会',
    passRateText: '通过率',
    practiceCount: '练习次数',
    viewAnswer: '查看答案',
    practice: '练习',
    markMastered: '标记已学会',
    markNotMastered: '标记未学会',
    markSuccess: '标记成功',
    pleaseSelectAnswer: '请选择答案',
    practiceSubmitFailed: '练习提交失败',
    singleChoice: '单选题',
    multipleChoice: '多选题',
    judgment: '判断题',
    fillBlank: '填空题',
    essay: '简答题',
    programming: '编程题',
    correctAnswer: '正确答案',
    wrongAnswer: '错误答案',
    analysis: '解析',
    yourAnswer: '你的答案',
    answerCorrect: '回答正确！',
    answerWrong: '回答错误',
    unanswered: '未作答',
    answered: '已答题',
    loadingMore: '加载中...',
    noMoreData: '没有更多数据',
    clickLoadMore: '点击加载更多',
    viewExam: '查看考试',
    current: '当前',
    prevQuestion: '上一题',
    nextQuestion: '下一题',
    questionNav: '答题卡',
    warning: '警告',
    leftExam: '检测到离开考试，已离开',
    chancesLeft: '次，剩余机会有限',
    reachedLimit: '离开次数已达上限，将自动交卷',
    leaveCount: '离开次数',
    remainingChances: '剩余',
    continueExam: '继续考试'
  },
  account: {
    basicInfo: '基本资料',
    editInfo: '编辑资料',
    realName: '姓名',
    username: '用户名',
    email: '邮箱',
    phone: '手机号',
    avatar: '头像',
    viewAvatar: '查看头像',
    changeAvatar: '更换头像',
    enterRealName: '请输入姓名',
    enterEmail: '请输入邮箱',
    enterPhone: '请输入手机号',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    enterCurrentPassword: '请输入当前密码',
    enterNewPassword: '请输入新密码',
    enterConfirmPassword: '请再次输入新密码',
    passwordChanged: '密码修改成功',
    passwordError: '当前密码错误',
    profileUpdated: '资料更新成功',
    avatarUpdated: '头像更新成功'
  },
  classChat: {
    members: '名成员',
    startTime: '开始时间',
    endTime: '结束时间',
    duration: '时长',
    minutes: '分钟',
    enterExam: '进入考试',
    viewExam: '查看考试',
    enterMessage: '输入消息...',
    send: '发送',
    muted: '你已被禁言',
    classMembers: '班级成员',
    owner: '创建者',
    admin: '管理员',
    member: '成员'
  }
}

export const en = {
  common: {
    home: 'Home',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    close: 'Close',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    save: 'Save',
    reset: 'Reset',
    back: 'Back',
    success: 'Success',
    failed: 'Failed',
    loading: 'Loading...',
    noData: 'No data',
    confirmDelete: 'Are you sure you want to delete?',
    confirmDeleteSubject: 'Are you sure you want to delete {name}?',
    confirmFinish: 'Are you sure you want to finish the exam?',
    confirmStart: 'Are you sure you want to start the exam?',
    confirmDeleteUser: 'Are you sure you want to delete user {username}?',
    tip: 'Tip',
    warning: 'Warning',
    loginFailed: 'Login failed',
    deleteSuccess: 'Deleted',
    deleteFailed: 'Delete failed',
    updateSuccess: 'Updated',
    createSuccess: 'Created',
    submitting: 'Submitting...',
    pleaseSelectRole: 'Please select role',
    all: 'All',
    name: 'Name',
    code: 'Code',
    department: 'Department',
    class: 'Class',
    user: 'User',
    admin: 'Admin',
    teacher: 'Teacher',
    student: 'Student',
    owner: 'Owner',
    member: 'Member',
    role: 'Role',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    phone: 'Phone',
    realName: 'Real Name',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    pleaseEnter: 'Please enter',
    pleaseSelect: 'Please select',
    notModifyLeaveEmpty: 'Leave empty to keep current',
    per: 'per',
    distribution: 'Distribution',
    remark: 'Remark',
    participation: 'Participations',
    exam: 'Exam',
    paper: 'Paper',
    question: 'Question',
    score: 'Score',
    time: 'Time',
    status: 'Status',
    statistics: 'Statistics',
    logs: 'Logs',
    overview: 'Overview',
    view: 'View',
    dashboard: 'Dashboard',
    account: 'Account',
    message: 'Message',
    language: 'Language',
    chinese: '中文',
    english: 'English',
    myClasses: 'My Classes',
    classChat: 'Class Chat',
    history: 'History',
    wrongQuestions: 'Wrong Questions',
    examList: 'Exam List',
    takeExam: 'Take Exam',
    examTake: 'Exam',
    viewDetail: 'View Detail',
    grade: 'Grade',
    monitor: 'Monitor',
    examMonitor: 'Exam Monitor',
    examStatistics: 'Exam Stats',
    examineeStatus: 'Status',
    totalPeople: 'Total',
    submitted: 'Submitted',
    notStarted: 'Not Started',
    ongoing: 'Ongoing',
    autoSubmitted: 'Auto-submitted',
    pending: 'Pending',
    finished: 'Finished',
    durationMinutes: 'min',
    start: 'Start',
    studentId: 'ID',
    submitTime: 'Submit Time',
    unknownSubject: 'Unknown',
    manage: 'Manage',
    subject: 'Subject',
    knowledgePoint: 'Knowledge Point',
    paperManage: 'Paper Manage',
    paperPreview: 'Paper Preview',
    questionManage: 'Question Manage',
    subjectManage: 'Subject Manage',
    examManage: 'Exam Manage',
    examRecord: 'Exam Record',
    examRecords: 'Exam Records',
    examRecordDetail: 'Exam Record Detail',
    viewRecords: 'View Records',
    examDetail: 'Exam Detail',
    systemLog: 'System Log',
    logManage: 'Log Management',
    userManage: 'User Manage',
    departmentManage: 'Department Manage',
    classManage: 'Class Manage',
    dataStatistics: 'Data Statistics',
    allSubjects: 'All Subjects',
    allStatus: 'All Status',
    prevQuestion: 'Prev',
    nextQuestion: 'Next',
    questionNav: 'Answer Sheet',
    createAndManage: 'Create and Manage Papers',
    createPaper: 'Create Paper',
    editPaper: 'Edit Paper',
    paperTitle: 'Paper Title',
    paperDesc: 'Paper Description',
    selectSubjectFirst: 'Select Subject',
    examDuration: 'Exam Duration',
    questionList: 'Question List',
    noQuestions: 'No questions, please add',
    confirmAdd: 'Confirm Add',
    questionTypeLabel: 'Question Type',
    selectQuestionTypeFirst: 'Select Question Type',
    publishAndManage: 'Publish and Manage Exams',
    publishExam: 'Publish Exam',
    published: 'Published',
    draft: 'Draft',
    totalScore: 'Total Score',
    passScore: 'Pass Score',
    preview: 'Preview',
    questionType: 'Question Type',
    questionContent: 'Question Content',
    addQuestion: 'Add Question',
    editQuestion: 'Edit Question',
    selectSubject: 'Subject',
    selectQuestionType: 'Question Type',
    enterQuestionContent: 'Enter question content',
    batchImport: 'Batch Import',
    leftCount: 'Leave Count',
    maxLeaveCount: 'Max Leave Count',
    leaveDetection: 'Leave Detection',
    shuffleQuestions: 'Shuffle Questions',
    shuffleOptions: 'Shuffle Options',
    passRate: 'Pass Rate',
    viewAfterExam: 'View After Exam',
    duration: 'Duration (minutes)',
    startTime: 'Start Time',
    endTime: 'End Time',
    title: 'Title',
    content: 'Content',
    options: 'Options',
    option: 'Option',
    addOption: 'Add Option',
    correctAnswer: 'Correct Answer',
    enterCorrectAnswer: 'Enter correct answer',
    enterScore: 'Enter score',
    studentAnswer: 'Student Answer',
    referenceAnswer: 'Reference',
    notAnswered: 'Not Answered',
    current: 'Current',
    unanswered: 'Unanswered',
    total: 'Total',
    type: 'Type',
    singleChoice: 'Single Choice',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True/False',
    fillBlank: 'Fill Blank',
    shortAnswer: 'Short Answer',
    pending: 'Pending',
    ongoing: 'Ongoing',
    finished: 'Finished',
    submitted: 'Submitted',
    notSubmitted: 'Not Submitted',
    autoSave: 'Auto Save',
    manualSave: 'Manual Save',
    submitExam: 'Submit Exam',
    timeRemaining: 'Time Remaining',
    seconds: 'seconds',
    minutes: 'minutes',
    hours: 'hours',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    total: 'Total',
    average: 'Average',
    count: 'Count',
    percent: 'Percent',
    date: 'Date',
    operation: 'Operation',
    method: 'Method',
    ip: 'IP Address',
    createTime: 'Create Time',
    updateTime: 'Update Time',
    inviteCode: 'Invite Code',
    shareInviteCode: 'Share invite code with classmates to join the class',
    viewLatest: 'View latest class updates',
    members: 'Members',
    messages: 'Messages',
    send: 'Send',
    join: 'Join',
    leave: 'Leave',
    upload: 'Upload',
    avatar: 'Avatar',
    about: 'About',
    version: 'Version',
    copyright: 'Copyright',
    clearCache: 'Clear Cache',
    changePassword: 'Change Password',
    editProfile: 'Edit Profile',
    welcome: 'Welcome',
    recentExam: 'Recent Exams',
    upcomingExam: 'Upcoming Exams',
    completedExam: 'Completed Exams',
    examNotice: 'Exam Notice',
    logRecent: 'Recent Operations',
    viewMore: 'View More',
    noMore: 'No more',
    page: 'Page',
    of: 'of',
    goToPage: 'Go to page',
    rowsPerPage: 'Rows per page',
    prevPage: 'Previous',
    nextPage: 'Next',
    firstPage: 'First',
    lastPage: 'Last',
    loginSuccess: 'Login successful',
    registerSuccess: 'Register successful',
    passwordChanged: 'Password changed successfully',
    profileUpdated: 'Profile updated successfully',
    pleaseLogin: 'Please login first',
    sessionExpired: 'Session expired, please login again',
    networkError: 'Network error',
    serverError: 'Server error',
    notFound: 'Not found',
    forbidden: 'Access denied',
    examStarted: 'Exam has started',
    examFinished: 'Exam has finished',
    examNotStarted: 'Exam has not started',
    examSubmitted: 'Exam submitted',
    leaveWarning: 'Leave detected',
    exceedLeaveCount: 'Exceeded leave count, exam auto-submitted',
    pleaseAnswerAll: 'Please answer all questions before submitting',
    confirmSubmit: 'Are you sure you want to submit?',
    questions: 'questions',
    savedSuccessfully: 'Saved successfully',
    saveFailed: 'Save failed',
    loadingMore: 'Loading more...',
    pullDownRefresh: 'Pull down to refresh',
    releaseRefresh: 'Release to refresh',
    refreshing: 'Refreshing...',
    enterExam: 'Enter Exam',
    viewPaper: 'View Paper',
    viewScore: 'View Score',
    viewAnalysis: 'View Analysis',
    scoreAnalysis: 'Score Analysis',
    scored: 'Scored',
    currentScore: 'Current Score',
    correct: 'Correct',
    wrong: 'Wrong',
    submitGrade: 'Submit Grade',
    practice: 'Practice',
    mastered: 'Mastered',
    notMastered: 'Not Mastered',
    correctRate: 'Correct Rate',
    difficulty: 'Difficulty',
    frequency: 'Error Frequency',
    publish: 'Publish',
    unpublish: 'Unpublish',
    start: 'Start',
    finish: 'Finish',
    extend: 'Extend',
    extendMinutes: 'Extend minutes',
    generate: 'Generate',
    import: 'Import',
    export: 'Export',
    copy: 'Copy',
    copied: 'Copied',
    copySuccess: 'Copy successful',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    invertSelect: 'Invert Selection',
    selectedCount: 'Selected {count} items',
    batchDelete: 'Batch Delete',
    batchOperation: 'Batch Operation',
    batchSuccess: 'Batch operation successful',
    batchFailed: 'Batch operation failed',
    selectDepartment: 'Select Department',
    selectQuestionType: 'Select Question Type',
    selectRole: 'Select Role',
    selectStatus: 'Select Status',
    selectDate: 'Select Date',
    startDate: 'Start Date',
    endDate: 'End Date',
    selectTime: 'Select Time',
    quickSelect: 'Quick Select',
    customRange: 'Custom Range',
    searchPlaceholder: 'Enter keyword',
    filterPlaceholder: 'Select filter',
    resetFilter: 'Reset Filter',
    applyFilter: 'Apply Filter',
    filterResult: '{count} results',
    sortAsc: 'Ascending',
    sortDesc: 'Descending',
    sortBy: 'Sort by',
    sortByName: 'Sort by name',
    sortByTime: 'Sort by time',
    sortByCount: 'Sort by count',
    sortByScore: 'Sort by score',
    ascending: 'Ascending',
    descending: 'Descending',
    show: 'Show',
    hide: 'Hide',
    expand: 'Expand',
    collapse: 'Collapse',
    toggle: 'Toggle',
    enable: 'Enable',
    disable: 'Disable',
    switch: 'Switch',
    on: 'On',
    off: 'Off',
    yes: 'Yes',
    no: 'No',
    unknown: 'Unknown',
    other: 'Other',
    pleaseWait: 'Please wait',
    processing: 'Processing...',
    complete: 'Complete',
    cancelProcess: 'Cancel',
    confirmCancel: 'Are you sure you want to cancel?',
    hasChanges: 'You have unsaved changes. Are you sure you want to leave?',
    unsavedChanges: 'Unsaved changes',
    discardChanges: 'Discard changes',
    saveChanges: 'Save changes',
    confirmLogout: 'Are you sure you want to logout?',
    confirmClearCache: 'Are you sure you want to clear cache? All local data will be deleted.',
    aboutSystem: 'About System',
    systemName: 'Online Exam System',
    systemDescription: 'An online exam system based on Vue + Spring Boot',
    developer: 'Developer',
    techStack: 'Tech Stack',
    contact: 'Contact',
    feedback: 'Feedback',
    help: 'Help',
    documentation: 'Documentation',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    agreement: 'User Agreement',
    iAgree: 'I agree',
    readAgreement: 'I have read and agree',
    mustAgree: 'You must agree to continue',
    validateFailed: 'Validation failed',
    validateSuccess: 'Validation successful',
    checkInput: 'Please check input',
    inputError: 'Input error',
    inputTooShort: 'Input too short',
    inputTooLong: 'Input too long',
    inputInvalid: 'Invalid input format',
    passwordNotMatch: 'Passwords do not match',
    passwordTooWeak: 'Password too weak',
    passwordChangedSuccess: 'Password changed successfully, please login again',
    profileUpdatedSuccess: 'Profile updated successfully',
    avatarUpdatedSuccess: 'Avatar updated successfully',
    examCreatedSuccess: 'Exam created successfully',
    examUpdatedSuccess: 'Exam updated successfully',
    examDeletedSuccess: 'Exam deleted successfully',
    examPublishedSuccess: 'Exam published successfully',
    examUnpublishedSuccess: 'Exam unpublished',
    publishedSuccess: 'Published successfully',
    examExtendedSuccess: 'Exam time extended',
    paperCreatedSuccess: 'Paper created successfully',
    paperUpdatedSuccess: 'Paper updated successfully',
    paperDeletedSuccess: 'Paper deleted successfully',
    questionCreatedSuccess: 'Question created successfully',
    questionUpdatedSuccess: 'Question updated successfully',
    questionDeletedSuccess: 'Question deleted successfully',
    questionImportedSuccess: 'Questions imported successfully',
    subjectCreatedSuccess: 'Subject created successfully',
    subjectUpdatedSuccess: 'Subject updated successfully',
    subjectDeletedSuccess: 'Subject deleted successfully',
    userCreatedSuccess: 'User created successfully',
    userUpdatedSuccess: 'User updated successfully',
    userDeletedSuccess: 'User deleted successfully',
    departmentCreatedSuccess: 'Department created successfully',
    departmentUpdatedSuccess: 'Department updated successfully',
    departmentDeletedSuccess: 'Department deleted successfully',
    classCreatedSuccess: 'Class created successfully',
    classUpdatedSuccess: 'Class updated successfully',
    classDeletedSuccess: 'Class deleted successfully',
    joinedClassSuccess: 'Joined class successfully',
    leftClassSuccess: 'Left class successfully',
    messageSentSuccess: 'Message sent successfully',
    examStartedSuccess: 'Exam started successfully',
    examFinishedSuccess: 'Exam finished successfully',
    examSubmittedSuccess: 'Exam submitted successfully',
    examGradedSuccess: 'Grading successful',
    wrongQuestionCreated: 'Wrong question record created',
    wrongQuestionUpdated: 'Wrong question record updated',
    wrongQuestionDeleted: 'Wrong question record deleted',
    statisticsUpdated: 'Statistics updated',
    logsCleared: 'Logs cleared',
    cacheCleared: 'Cache cleared',
    networkTimeout: 'Network timeout',
    connectionFailed: 'Connection failed',
    serviceUnavailable: 'Service unavailable',
    maintenance: 'System maintenance',
    upgrade: 'System upgrade',
    comingSoon: 'Coming soon',
    underDevelopment: 'Under development',
    featureNotAvailable: 'Feature not available',
    permissionDenied: 'Permission denied',
    needAdmin: 'Admin permission required',
    needTeacher: 'Teacher permission required',
    needStudent: 'Student permission required',
    notInClass: 'Not in class',
    classFull: 'Class full',
    inviteCodeInvalid: 'Invalid invite code',
    inviteCodeExpired: 'Invite code expired',
    alreadyInClass: 'Already in class',
    examNotFound: 'Exam not found',
    paperNotFound: 'Paper not found',
    questionNotFound: 'Question not found',
    userNotFound: 'User not found',
    departmentNotFound: 'Department not found',
    classNotFound: 'Class not found',
    subjectNotFound: 'Subject not found',
    recordNotFound: 'Record not found',
    logNotFound: 'Log not found',
    wrongQuestionNotFound: 'Wrong question not found',
    cannotDelete: 'Cannot delete',
    cannotDeleteSelf: 'Cannot delete yourself',
    cannotDeleteAdmin: 'Cannot delete admin',
    cannotUpdate: 'Cannot update',
    cannotCreate: 'Cannot create',
    hasChildren: 'Has children, cannot delete',
    inUse: 'In use, cannot delete',
    examInProgress: 'Exam in progress, cannot modify',
    examFinishedCannotEdit: 'Exam finished, cannot modify',
    paperInUse: 'Paper in use, cannot delete',
    questionInUse: 'Question in use, cannot delete',
    subjectInUse: 'Subject in use, cannot delete',
    departmentInUse: 'Department in use, cannot delete',
    classInUse: 'Class in use, cannot delete',
    userInUse: 'User in use, cannot delete',
    pleaseFillAll: 'Please fill all required fields',
    pleaseFillRequired: 'Please fill required fields',
    pleaseSelectRequired: 'Please select required fields',
    pleaseUploadRequired: 'Please upload required files',
    formatNotSupported: 'Format not supported',
    fileTooLarge: 'File too large',
    fileTooSmall: 'File too small',
    uploadFailed: 'Upload failed',
    uploadSuccess: 'Upload successful',
    downloading: 'Downloading...',
    downloadSuccess: 'Download successful',
    downloadFailed: 'Download failed',
    exporting: 'Exporting...',
    exportSuccess: 'Export successful',
    exportFailed: 'Export failed',
    importing: 'Importing...',
    importSuccess: 'Import successful',
    importFailed: 'Import failed',
    generating: 'Generating...',
    generateSuccess: 'Generate successful',
    generateFailed: 'Generate failed',
    analyzing: 'Analyzing...',
    analysisSuccess: 'Analysis successful',
    analysisFailed: 'Analysis failed',
    calculating: 'Calculating...',
    calculationSuccess: 'Calculation successful',
    calculationFailed: 'Calculation failed',
    synchronizing: 'Synchronizing...',
    syncSuccess: 'Sync successful',
    syncFailed: 'Sync failed',
    refreshingData: 'Refreshing data...',
    refreshSuccess: 'Refresh successful',
    refreshFailed: 'Refresh failed',
    loadingData: 'Loading data...',
    loadSuccess: 'Load successful',
    loadFailed: 'Load failed',
    savingData: 'Saving data...',
    submittingData: 'Submitting data...',
    deletingData: 'Deleting data...',
    updatingData: 'Updating data...',
    creatingData: 'Creating data...',
    processingData: 'Processing data...',
    validatingData: 'Validating data...',
    dataValidated: 'Data validated',
    dataValidationFailed: 'Data validation failed',
    dataFormatError: 'Data format error',
    dataMissing: 'Data missing',
    dataDuplicate: 'Data duplicate',
    dataConflict: 'Data conflict',
    dataOutOfRange: 'Data out of range',
    dataNotAllowed: 'Data not allowed',
    dataInvalid: 'Data invalid',
    connectionEstablished: 'Connection established',
    connectionLost: 'Connection lost',
    reconnecting: 'Reconnecting...',
    reconnected: 'Reconnected',
    reconnectFailed: 'Reconnect failed',
    offlineMode: 'Offline mode',
    onlineMode: 'Online mode',
    autoReconnect: 'Auto reconnect',
    manualReconnect: 'Manual reconnect',
    checkNetwork: 'Please check network connection',
    checkServer: 'Please check server status',
    checkInternet: 'Please check internet connection',
    tryAgainLater: 'Please try again later',
    contactSupport: 'Please contact support',
    errorOccurred: 'An error occurred',
    unknownError: 'Unknown error',
    unexpectedError: 'Unexpected error',
    systemError: 'System error',
    applicationError: 'Application error',
    databaseError: 'Database error',
    authenticationError: 'Authentication error',
    authorizationError: 'Authorization error',
    configurationError: 'Configuration error',
    initializationError: 'Initialization error',
    runtimeError: 'Runtime error',
    validationError: 'Validation error',
    businessError: 'Business error',
    networkErrorRetry: 'Network error, please retry',
    serverErrorRetry: 'Server error, please retry',
    timeoutRetry: 'Request timeout, please retry',
    retry: 'Retry',
    retryLater: 'Retry later',
    skip: 'Skip',
    ignore: 'Ignore',
    continue: 'Continue',
    abort: 'Abort',
    retryCount: 'Retry count: {count}',
    maxRetryReached: 'Max retry reached',
    pleaseTryAgain: 'Please try again',
    pleaseContactAdmin: 'Please contact admin',
    pleaseCheckLogs: 'Please check logs',
    pleaseReportIssue: 'Please report issue',
    thankYou: 'Thank you',
    welcomeBack: 'Welcome back',
    hello: 'Hello',
    goodbye: 'Goodbye',
    haveANiceDay: 'Have a nice day',
    seeYouLater: 'See you later',
    goodLuck: 'Good luck',
    congratulations: 'Congratulations',
    wellDone: 'Well done',
    excellent: 'Excellent',
    greatJob: 'Great job',
    niceWork: 'Nice work',
    thankYouForYourFeedback: 'Thank you for your feedback',
    weValueYourFeedback: 'We value your feedback',
    yourOpinionMatters: 'Your opinion matters',
    pleaseShareYourThoughts: 'Please share your thoughts',
    helpUsImprove: 'Help us improve',
    stayTuned: 'Stay tuned',
    comingSoonMessage: 'More exciting features coming soon',
    newFeatures: 'New Features',
    improvedFeatures: 'Improved Features',
    bugFixes: 'Bug Fixes',
    performanceImprovements: 'Performance Improvements',
    securityUpdates: 'Security Updates',
    stabilityImprovements: 'Stability Improvements',
    userExperience: 'User Experience',
    interfaceImprovements: 'Interface Improvements',
    accessibilityImprovements: 'Accessibility Improvements',
    internationalization: 'Internationalization',
    localization: 'Localization',
    multiLanguage: 'Multi-language Support',
    responsiveDesign: 'Responsive Design',
    mobileOptimization: 'Mobile Optimization',
    tabletOptimization: 'Tablet Optimization',
    desktopOptimization: 'Desktop Optimization',
    crossPlatform: 'Cross-platform Support',
    offlineSupport: 'Offline Support',
    realTime: 'Real-time Sync',
    cloudSync: 'Cloud Sync',
    dataBackup: 'Data Backup',
    dataRecovery: 'Data Recovery',
    dataExport: 'Data Export',
    dataImport: 'Data Import',
    dataMigration: 'Data Migration',
    dataIntegration: 'Data Integration',
    apiIntegration: 'API Integration',
    thirdPartyIntegration: 'Third-party Integration',
    pluginSupport: 'Plugin Support',
    extensibility: 'Extensibility',
    customization: 'Customization',
    flexibility: 'Flexibility',
    scalability: 'Scalability',
    reliability: 'Reliability',
    availability: 'Availability',
    performance: 'Performance',
    security: 'Security',
    privacy: 'Privacy',
    compliance: 'Compliance',
    standards: 'Standards',
    bestPractices: 'Best Practices',
    documentation: 'Documentation',
    support: 'Support',
    community: 'Community',
    openSource: 'Open Source',
    contribution: 'Contribution',
    license: 'License',
    copyrightYear: '2024',
    allRightsReserved: 'All rights reserved',
    madeWithLove: 'Made with love',
    poweredBy: 'Powered by {name}',
    builtWith: 'Built with {name}',
    versionInfo: 'Version {version}',
    buildNumber: 'Build {build}',
    buildDate: 'Build Date {date}',
    environment: 'Environment: {env}',
    debugMode: 'Debug Mode',
    productionMode: 'Production Mode',
    developmentMode: 'Development Mode',
    stagingMode: 'Staging Mode',
    testMode: 'Test Mode',

    maintenanceMode: 'Maintenance Mode',
    readOnlyMode: 'Read-only Mode',
    safeMode: 'Safe Mode',
    emergencyMode: 'Emergency Mode',
    recoveryMode: 'Recovery Mode',
    setupMode: 'Setup Mode',
    wizardMode: 'Wizard Mode',
    tutorialMode: 'Tutorial Mode',
    beginnerMode: 'Beginner Mode',
    advancedMode: 'Advanced Mode',
    expertMode: 'Expert Mode',
    adminMode: 'Admin Mode',
    guestMode: 'Guest Mode',
    anonymousMode: 'Anonymous Mode',
    authenticatedMode: 'Authenticated Mode',
    authorizedMode: 'Authorized Mode',
    restrictedMode: 'Restricted Mode',
    lockedMode: 'Locked Mode',
    unlockedMode: 'Unlocked Mode',
    activeMode: 'Active Mode',
    inactiveMode: 'Inactive Mode',
    suspendedMode: 'Suspended Mode',
    resumedMode: 'Resumed Mode',
    terminatedMode: 'Terminated Mode',
    completedMode: 'Completed Mode',
    pendingMode: 'Pending Mode',
    processingMode: 'Processing Mode',
    failedMode: 'Failed Mode',
    successMode: 'Success Mode',
    warningMode: 'Warning Mode',
    errorMode: 'Error Mode',
    infoMode: 'Info Mode',
    debugModeLabel: 'Debug',
    traceMode: 'Trace',
    verboseMode: 'Verbose',
    quietMode: 'Quiet',
    silentMode: 'Silent',
    normalMode: 'Normal',
    strictMode: 'Strict',
    relaxedMode: 'Relaxed',
    lenientMode: 'Lenient',
    strictValidation: 'Strict Validation',
    relaxedValidation: 'Relaxed Validation',
    lenientValidation: 'Lenient Validation',
    strictParsing: 'Strict Parsing',
    relaxedParsing: 'Relaxed Parsing',
    lenientParsing: 'Lenient Parsing',
    strictFormatting: 'Strict Formatting',
    relaxedFormatting: 'Relaxed Formatting',
    lenientFormatting: 'Lenient Formatting',
    strictChecking: 'Strict Checking',
    relaxedChecking: 'Relaxed Checking',
    lenientChecking: 'Lenient Checking',
    strictModeEnabled: 'Strict mode enabled',
    relaxedModeEnabled: 'Relaxed mode enabled',
    lenientModeEnabled: 'Lenient mode enabled',
    strictModeDisabled: 'Strict mode disabled',
    relaxedModeDisabled: 'Relaxed mode disabled',
    lenientModeDisabled: 'Lenient mode disabled',
    enableStrictMode: 'Enable strict mode',
    disableStrictMode: 'Disable strict mode',
    toggleStrictMode: 'Toggle strict mode',
    currentMode: 'Current mode',
    modeChanged: 'Mode changed',
    modeChangeFailed: 'Mode change failed',
    cannotChangeMode: 'Cannot change mode',
    modeNotAvailable: 'Mode not available',
    modeRestricted: 'Mode restricted',
    modeLocked: 'Mode locked',
    modeUnlocked: 'Mode unlocked',
    modeActivated: 'Mode activated',
    modeDeactivated: 'Mode deactivated',
    modeSuspended: 'Mode suspended',
    modeResumed: 'Mode resumed',
    modeTerminated: 'Mode terminated',
    modeCompleted: 'Mode completed',
    modePending: 'Mode pending',
    modeProcessing: 'Mode processing',
    modeFailed: 'Mode failed',
    modeSuccess: 'Mode success',
    modeWarning: 'Mode warning',
    modeError: 'Mode error',
    modeInfo: 'Mode info',
    modeDebug: 'Mode debug',
    modeTrace: 'Mode trace',
    modeVerbose: 'Mode verbose',
    modeQuiet: 'Mode quiet',
    modeSilent: 'Mode silent',
    modeNormal: 'Mode normal',
    languageChanged: 'Language changed',
    languageChangeFailed: 'Language change failed',
    cannotChangeLanguage: 'Cannot change language',
    languageNotAvailable: 'Language not available',
    languageRestricted: 'Language restricted',
    languageLocked: 'Language locked',
    languageUnlocked: 'Language unlocked',
    languageActivated: 'Language activated',
    languageDeactivated: 'Language deactivated',
    languageSuspended: 'Language suspended',
    languageResumed: 'Language resumed',
    languageTerminated: 'Language terminated',
    languageCompleted: 'Language completed',
    languagePending: 'Language pending',
    languageProcessing: 'Language processing',
    languageFailed: 'Language failed',
    languageSuccess: 'Language success',
    languageWarning: 'Language warning',
    languageError: 'Language error',
    languageInfo: 'Language info',
    languageDebug: 'Language debug',
    languageTrace: 'Language trace',
    languageVerbose: 'Language verbose',
    languageQuiet: 'Language quiet',
    languageSilent: 'Language silent',
    languageNormal: 'Language normal',
    statusPending: 'Pending',
    statusOngoing: 'Ongoing',
    statusFinished: 'Finished',
    allDepartments: 'All Departments',
    noLogData: 'No log data',
    totalRecords: 'Total {total} records',
    year: 'y',
    month: 'm',
    day: 'd',
    saving: 'Saving...',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Save failed',
    creator: 'Creator',
    unknownUser: 'Unknown',
    classMembers: 'Class Members',
    muted: 'Muted',
    sendFailed: 'Send failed',
    enterMessage: 'Enter message...',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    classMessage: 'Class Messages',
    systemNotification: 'System Notifications',
    noClassMessage: 'No class messages',
    noSystemNotification: 'No system notifications',
    noMessage: 'No messages',
    startExam: 'Exam started',
    publishNotice: 'Notice published',
    createUser: 'Create User',
    updateUser: 'Update User',
    deleteUser: 'Delete User',
    createDepartment: 'Create Department',
    updateDepartment: 'Update Department',
    deleteDepartment: 'Delete Department',
    createClass: 'Create Class',
    updateClass: 'Update Class',
    deleteClass: 'Delete Class',
    createExam: 'Create Exam',
    updateExam: 'Update Exam',
    deleteExam: 'Delete Exam',
    editExam: 'Edit Exam',
    basicInfo: 'Basic Information',
    viewAnswer: 'View Answer',
    allExams: 'All Exams',
    questionCount: 'Question Count',
    judgment: 'True/False',
    essay: 'Short Answer',
    inviteMembers: 'Invite Members',
    importText: 'Import Text',
    formatDesc: 'Format Description',
    importNote: 'Import Note',
    pasteQuestionText: 'Paste question text',
    target: 'Target',
    create: 'Create'
  },
  teacher: {
    enterClassName: 'Enter class name',
    createClass: 'Create Class',
    noClasses: 'No classes yet, create your first class',
    examTitle: 'Exam Title',
    enterExamTitle: 'Enter exam title',
    selectPaper: 'Select Paper',
    selectClass: 'Select Class',
    examDuration: 'Duration (minutes)',
    duration: 'Duration',
    enterDuration: 'Enter duration',
    startDate: 'Start Date',
    selectDate: 'Select date',
    startTime: 'Start Time',
    selectTime: 'Select time',
    examSettings: 'Exam Settings',
    passRate: 'Pass Rate',
    default60: 'Default 60',
    shuffleQuestions: 'Shuffle Questions',
    shuffleQuestionsDesc: 'Questions will be randomly ordered',
    shuffleOptions: 'Shuffle Options',
    shuffleOptionsDesc: 'Options will be randomly ordered',
    leaveDetection: 'Leave Detection',
    leaveDetectionDesc: 'Detect leaving the exam page',
    maxLeaveCount: 'Max Leave Count',
    maxLeaveCountDesc: 'Auto-submit after exceeding count',
    allowViewAfterExam: 'Allow View After Exam',
    allowViewAfterExamDesc: 'View paper and answers after exam',
    selectStartTime: 'Select start time',
    publishExam: 'Publish Exam',
    inviteMembers: 'Invite Members',
    grading: 'Grading...',
    pleaseGradeAtLeastOne: 'Please grade at least one question',
    gradeSuccess: 'Grading successful',
    gradeFailed: 'Grading failed',
    questionSettings: 'Question Settings',
    searchQuestion: 'Search Question',
    clearSelection: 'Clear Selection',
    currentSubject: 'Current Subject',
    batchSetScore: 'Batch Set Score',
    selectQuestionType: 'Select Question Type',
    scoreHint: 'Score',
    applyToSelected: 'Apply to Selected',
    selected: 'Selected',
    setScore: 'Set Score',
    selectAtLeastOneQuestion: 'Please select at least one question',
    selectSubjectFirst: 'Select subject first',
    subjectNotFound: 'Associated subject not found, please reselect',
    batchSetSuccess: 'Batch set successful',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    singleChoice: 'Single Choice',
    multipleChoice: 'Multiple Choice',
    judgment: 'True/False',
    fillBlank: 'Fill Blank',
    essay: 'Short Answer',
    programming: 'Programming',
    paperManagement: 'Paper Management',
    paperManagementDesc: 'Create and manage papers',
    autoGenerate: 'Auto Generate',
    createPaper: 'Create Paper',
    editPaper: 'Edit Paper',
    paperTitle: 'Paper Title',
    enterPaperTitle: 'Enter paper title',
    totalScore: 'Total Score',
    passScore: 'Pass Score',
    paperDuration: 'Duration',
    minutes: 'mins',
    preview: 'Preview',
    publish: 'Publish',
    confirmPublish: 'Are you sure you want to publish?',
    paperPublished: 'Paper published successfully',
    confirmDelete: 'Are you sure you want to delete?',
    autoCalculate: 'Auto Calculate',
    enterDuration: 'Enter duration',
    enterPassRate: 'Enter pass rate',
    questionCountScore: 'Question Count & Score',
    count: 'Count',
    perQuestion: 'Per Question',
    scoreUnit: 'pts',
    generateTip1: 'System will randomly select questions based on your settings',
    generateTip2: 'Ensure question count does not exceed available questions in the bank',
    generatePaper: 'Generate Paper',
    generateResult: 'Generate Result',
    viewPaper: 'View Paper',
    getPaperInfoFailed: 'Failed to get paper info',
    selectSubject: 'Select Subject',
    selectQuestionTypeFirst: 'Select question type',
    enterScore: 'Enter score'
  },
  admin: {
    allDepartments: 'All Departments'
  },
  login: {
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: 'Enter password',
    student: 'Student',
    teacher: 'Teacher',
    admin: 'Admin',
    studentNotFound: 'Student account not found',
    teacherNotFound: 'Teacher account not found',
    adminNotFound: 'Admin account not found',
    loginFailed: 'Login failed',
    enterUsernamePassword: 'Please enter username and password'
  },
  register: {
    title: 'Create Account',
    subtitle: 'Select role and fill registration information',
    confirmPasswordPlaceholder: 'Confirm password',
    selectDepartment: 'Select department',
    haveAccount: 'Already have an account? Login',
    usernameLength: 'Username must be 3-20 characters',
    passwordLength: 'Password must be 6-20 characters',
    passwordMismatch: 'Passwords do not match',
    registerSuccess: 'Registered',
    registerFailed: 'Registration failed'
  },
  dashboard: {
    welcome: 'Welcome back',
    totalUsers: 'Total Users',
    count: 'Count',
    departmentCount: 'Department Count',
    classCount: 'Class Count',
    paperCount: 'Paper Count',
    questionCount: 'Question Count',
    examCount: 'Exam Count',
    pendingExams: 'Pending Exams',
    completedExams: 'Completed',
    wrongCount: 'Wrong Count',
    averageScore: 'Average Score',
    scoreUnit: 'pts',
    myClasses: 'My Classes',
    examList: 'Exam List',
    examHistory: 'Exam History',
    systemManagement: 'System Management',
    userManagement: 'User Management',
    departmentManagement: 'Department Management',
    classManagement: 'Class Management',
    dataStatistics: 'Data Statistics',
    systemLogs: 'System Logs',
    recentLogs: 'Recent Operation Logs',
    recentExams: 'Recent Exams',
    manageExams: 'Manage Exams',
    upcomingExams: 'Upcoming Exams',
    allExams: 'All Exams',
    enterExam: 'Enter Exam',
    waiting: 'Waiting',
    noUpcomingExams: 'No upcoming exams',
    scoreAnalysis: 'Score Analysis',
    examTips: 'Exam Tips',
    tip1: 'Keep network stable during exam',
    tip2: 'Do not switch pages frequently during exam',
    tip3: 'Answers auto-save, but manual submission is recommended',
    tip4: 'View wrong answer analysis after exam',
    subjectManagement: 'Subject Management',
    questionManagement: 'Question Management',
    paperManagement: 'Paper Management',
    examManagement: 'Exam Management',
    minutes: 'mins'
  },
  student: {
    loadingExam: 'Loading exam...',
    viewLatest: 'View latest class updates',
    enterClassCode: 'Enter class code',
    joinClass: 'Join Class',
    noClass: 'No classes yet, enter code to join',
    joinSuccess: 'Joined class successfully',
    joinFailed: 'Failed to join class',
    loadFailed: 'Failed to load class list',
    pleaseLogin: 'Please login first',
    networkError: 'Network error',
    owner: 'Owner',
    admin: 'Admin',
    member: 'Member',
    justNow: 'Just now',
    minutesAgo: 'm ago',
    hoursAgo: 'h ago',
    ago: '',
    examStarted: 'Exam started',
    examPublished: 'Exam published',
    viewAndJoin: 'View and join exams',
    searchExam: 'Search exam',
    noExams: 'No exams',
    autoSubmitted: 'Auto-submitted',
    enterExam: 'Enter Exam',
    waiting: 'Waiting',
    viewDetail: 'View Detail',
    examInProgress: 'Exam in progress',
    submitExam: 'Submit Exam',
    examNotice: 'Exam Notice',
    timeRemaining: 'Time remaining',
    submitSuccess: 'Submitted successfully',
    submitFailed: 'Submit failed',
    confirmSubmit: 'Are you sure you want to submit?',
    viewExamHistory: 'View exam history',
    noHistory: 'No exam records',
    submitTime: 'Submit time',
    viewAnalysis: 'View score analysis',
    totalExams: 'Total Exams',
    avgScore: 'Average Score',
    passRate: 'Pass Rate',
    subjectScores: 'Subject Scores',
    exams: ' exams',
    answerStats: 'Answer Statistics',
    correctCount: 'Correct',
    wrongCount: 'Wrong',
    skippedCount: 'Skipped',
    wrongBookDesc: 'Review wrong questions',
    allSubjects: 'All Subjects',
    allStatus: 'All Status',
    notMastered: 'Not Mastered',
    mastered: 'Mastered',
    passRateText: 'Pass Rate',
    practiceCount: 'Practice Count',
    viewAnswer: 'View Answer',
    practice: 'Practice',
    markMastered: 'Mark as Mastered',
    markNotMastered: 'Mark as Not Mastered',
    markSuccess: 'Marked successfully',
    pleaseSelectAnswer: 'Please select answer',
    practiceSubmitFailed: 'Practice submit failed',
    singleChoice: 'Single Choice',
    multipleChoice: 'Multiple Choice',
    judgment: 'True/False',
    fillBlank: 'Fill Blank',
    essay: 'Short Answer',
    programming: 'Programming',
    correctAnswer: 'Correct Answer',
    wrongAnswer: 'Wrong Answer',
    analysis: 'Analysis',
    yourAnswer: 'Your Answer',
    answerCorrect: 'Correct!',
    answerWrong: 'Incorrect',
    unanswered: 'Not answered',
    answered: 'Answered',
    loadingMore: 'Loading...',
    noMoreData: 'No more data',
    clickLoadMore: 'Click to load more',
    viewExam: 'View Exam',
    current: 'Current',
    prevQuestion: 'Prev',
    nextQuestion: 'Next',
    questionNav: 'Answer Sheet',
    warning: 'Warning',
    leftExam: 'Left exam detected, left ',
    chancesLeft: ' times, limited chances remaining',
    reachedLimit: 'Leave count exceeded, exam will auto-submit',
    leaveCount: 'Leave Count',
    remainingChances: 'Remaining ',
    continueExam: 'Continue Exam'
  },
  account: {
    basicInfo: 'Basic Information',
    editInfo: 'Edit Profile',
    realName: 'Name',
    username: 'Username',
    email: 'Email',
    phone: 'Phone',
    avatar: 'Avatar',
    viewAvatar: 'View Avatar',
    changeAvatar: 'Change Avatar',
    enterRealName: 'Enter name',
    enterEmail: 'Enter email',
    enterPhone: 'Enter phone',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    enterConfirmPassword: 'Confirm new password',
    passwordChanged: 'Password changed successfully',
    passwordError: 'Current password incorrect',
    profileUpdated: 'Profile updated successfully',
    avatarUpdated: 'Avatar updated successfully'
  },
  classChat: {
    members: ' members',
    startTime: 'Start Time',
    endTime: 'End Time',
    duration: 'Duration',
    minutes: ' mins',
    enterExam: 'Enter Exam',
    viewExam: 'View Exam',
    enterMessage: 'Enter message...',
    send: 'Send',
    muted: 'You are muted',
    classMembers: 'Class Members',
    owner: 'Owner',
    admin: 'Admin',
    member: 'Member'
  }
}

export const useLang = () => {
  const getLanguage = () => {
    let lang = 'zh'
    try {
      lang = uni.getStorageSync('language') || lang
    } catch (e) {
      try {
        lang = localStorage.getItem('language') || lang
      } catch (e2) {
        lang = lang
      }
    }
    return lang
  }

  const currentLang = ref(getLanguage())
  const messages = currentLang.value === 'zh' ? zh : en

  const t = (key) => {
    const keys = key.split('.')
    let result = messages
    for (const k of keys) {
      if (result && typeof result === 'object') {
        result = result[k]
      } else {
        return key
      }
    }
    return result || key
  }

  const changeLang = (lang) => {
    currentLang.value = lang
    try {
      uni.setStorageSync('language', lang)
    } catch (e) {
      try {
        localStorage.setItem('language', lang)
      } catch (e2) {
        console.error('Failed to save language')
      }
    }
  }

  const getCurrentLang = () => currentLang.value

  return { t, changeLang, getCurrentLang, currentLang }
}
